### ISSUE TITLE
Huge memory allocation during partial tucker decomposition on a sparse tensor

### ISSUE THREAD

**Issue by mitarj** [tensorly/tensorly#101]
I'm not sure where should I post this since the sparse backend works properly only in the `Quansight:sparse-master` branch which is what I used, but I guess here it will be more visible.
### The problem
I have a sparse tensor of size 15000x15000x10000 with about 1.5 million nonzero values. I am doing a partial tucker decomposition like this:
`core, factors = partial_tucker(sparse_tensor, modes=[0, 2], ranks=[64, 64])`
But Google Colab crashes and the log says that there was a ~60GB memory allocation attempt. I am not sure if somewhere there was a densification operation because I set the flag `SPARSE_AUTO_DENSIFY` to `0` and no errors were thrown. I can provide the sparse tensor if needed.

**Comment by asmeurer** [comment]
Are you using the partial_tucker from `tensorly.contrib.sparse.decomposition` (or using `set_backend('sparse')`? The `partial_tucker` from `tensorly.decomposition` is not sparse-safe by default unless you set the backend. 

Assuming you are using the sparse version, is there a traceback with the crash?

**Comment by mitarj** [comment]
I used the version from `tensorly.contrib.sparse.decomposition`. My tensor is a `COO` tensor from the `sparse` library. Interestingly, changing the core size from 64 to 16 caused an attempted ~17GB allocation, changing it to 8 caused an attempted ~13GB allocation. I run the code in Google Colab (memory limit there is ~12GB), so I'm not sure where the traceback is stored, if you point me to it I'll happily submit it.

**Comment by asmeurer** [comment]
It depends on how it crashed. If it crashed with a MemoryError, you should see a traceback. If it crashed with something like SIGABRT you wouldn't. You can also try interrupting the kernel while it is running and getting a traceback from that.

**Comment by asmeurer** [comment]
Also does it help if you do `init='random'`? I'm not sure if `init='svd'` (the default) has been tested with sparse tensors.

**Comment by mitarj** [comment]
There is nothing printed in the notebook. Colab just notifies me that the runtime crashed due to a large attempted malloc. When I interrupt the execution after ~20s I just get a plain `KeyboardInterrupt`.

I tried running it with `init='random'` and it worked! The catch is it took about an hour to complete.
`memit` gave the following result: `peak memory: 4259.46 MiB, increment: 3931.23 MiB` (with core dimension 8). Thank you very much, I would have never guessed that the `init` parameter might be a problem.

**Comment by asmeurer** [comment]
OK, so I think the init='svd' hasn't been fixed to be sparse safe. I don't know how hard it is to fix. @JeanKossaifi how should we address this? Change the default for the sparse backend? Or raise a warning?

**Comment by JeanKossaifi** [comment]
Sounds like a good solution. We can change the default to 'random' in the sparse, wrapped version?

**Comment by asmeurer** [comment]
I think so. We can wrap it manually instead of using the `wrap` decorator. Or extend `wrap` so it can modify default values, like `wrap(partial_tucker, init='random')`. It should be documented over at https://github.com/tensorly/tensorly/pull/89 in any case.

**Comment by devanshuarya** [comment]
Hi @mitarj 
I am facing issue with mismatch in backend while decomposing a COO matrix using `from tensorly.contrib.sparse.decomposition import parafac`. 
Can you also share the branch of tensorly that you are using?

**Comment by dswalter** [comment]
@devanshuarya, I'm pretty sure the same issue is present with the parafac algorithm initializing using the default 'svd' option which is not necessarily sparse-safe. If you pass in the argument `init='random'` to that `parafac` function you imported, you should be able to decompose your input COO tensor without inadvertently dense-ifying it.

**Comment by asmeurer** [comment]
parafac was not sparse safe in master until just today, when #102 was merged.
