### ISSUE TITLE
About RPCA implementation

### ISSUE THREAD

**Issue by eduardocalil** [tensorly/tensorly#108]
Hello guys,

I'm writting a paper that implements RPCA to identify anomalous traffic in cyber networks. In order to do that, I'm using this brilliant library. I have read several papers about Robust PCA algorithm, but I found none that described the use of the parameter `reg_J`. Can someone please explain it to me or send me a link of the paper that was used to implement this RPCA version?

Thank you very much for your attention!

**Comment by JeanKossaifi** [comment]
Thanks for the kind words, glad you're finding it useful.

The `reg_J` parameter is just a scaling factor on the nuclear norm of the unfoldings in the objective function (See the objective function, in the note section of the [doc](http://tensorly.org/stable/modules/generated/tensorly.decomposition.robust_pca.html#tensorly.decomposition.robust_pca)). That objective function is optimized using the augmented Lagrangian method. Note that by default `reg_J=1`.

I also wrote a [blog post](http://jeankossaifi.com/blog/rpca.html) about Tensor RPCA.

**Comment by eduardocalil** [comment]
Thanks. It was very useful. However, if possible, I'd like to know where you found the possibility of adding this scaling factor to the Nuclear Norm. Because in all the other sources that I read, there was only a scaling factor multipling the L1 norm, which in this code is named `reg_E`.


![CodeCogsEqn](https://user-images.githubusercontent.com/14843060/56083709-275d9980-5dff-11e9-8a61-a8e1ca403f50.gif)

**Comment by JeanKossaifi** [comment]
It is just an implementation detail, to allow for more flexible usage.
You could want to optimise, for instance, for lambda in [0, 1]:
`lambda*nuclear_norm + (1 - lambda)*norm_1`.

You can get the case you mention by just leaving `reg_J=1`.
