### ISSUE TITLE
BUG:non_negative_tucker has no modes, lacked of modes=list(range(tl.ndim(tensor)))

### ISSUE THREAD

**Issue by moicesong** [tensorly/tensorly#109]

**Comment by JeanKossaifi** [comment]
Hi @moicesong,
I do not understand your issue. 
Are you perhaps suggesting to add a partial_non_negative_tucker where one is able to specify the modes of the decomposition? 
If you have a code that doesn't run, can you provide a minimal code to reproduce your issue?

**Comment by moicesong** [comment]
Hi @JeanKossaifi 
I have find a bug,when I run a example(eg is the follow).and then I find your code lacked of 'modes'.
 when I add code of 'modes = list(range(tl.ndim(tensor)))', the bug disappear.
( eg: 
x = np.arange(0.1,12.1).reshape(3,4)
non_negative_tucker(x,2,n_iter_max = 10,init ='svd',tol = 0.0001,random_state=None, verbose=False, ranks=None)
)

**Comment by JeanKossaifi** [comment]
Thanks for reporting @moicesong.
I don't have any issue with the code on Master, which version are you running? 
(You can get it via `import tensorly; tensorly.__version__`)

**Comment by moicesong** [comment]
@JeanKossaifi  the version is '0.4.3'

**Comment by JeanKossaifi** [comment]
This was fixed in master by 5ec54f47d56515eca3d28ae3826462433dd95ccb.
Updating to Master will fix your issue.
