### ISSUE TITLE
Tensorflow backend with graph mode

### ISSUE THREAD

**Issue by neen113** [tensorly/tensorly#110]
I was wondering if there is any way to work with tensorflow backend while tensors are in graph mode and are not EagorTensors.

**Comment by JeanKossaifi** [comment]
Based on my experience with other frameworks, I believe this would involve some rewriting but I have not worked on this, especially since eager mode is now the default mode in TensorFlow.

Can be interesting to have if you are interested in working on this though!

**Comment by craymichael** [comment]
I am currently working on this and will put up a pull request soon.

**Comment by JeanKossaifi** [comment]
Great, looking forward to it @craymichael

**Comment by craymichael** [comment]
I have graph execution working for Tucker decomposition and have enabled a user to use their own graph, `tf.Session`, etc. The numpy implementation of SVD is wrapped in a `tf.py_function`, but the TF version will likely be faster (at least for larger matrices). Each loop is now a `tf.while_loop`. It'll take a bit to extend to CP, regression, etc. with my current workload, but it'll get done

**Comment by JeanKossaifi** [comment]
Hi @craymichael,
If the integration was transparent it would be ideal but since it requires wrapping things (e.g. in tf.while_loop, etc) it might make more sense to simply write a graph-based version of TensorLy? The syntax might become too convoluted if the code is littered with, e.g. `if tl.get_backend() == 'tensorflow_graph'`.
We can make a small mockup with few functionalities based on the commits you've already made and see if there are speed gains? Since tensorflow is eager by default i would hope the difference is not too large.

**Comment by craymichael** [comment]
I agree - transparency would be ideal, however, any loop-based functionality cannot be kept as is. The only way graph-based execution can be kept as-is would be if the symbolic tensors (decomposed components, error, etc.) were executed each loop. This gives user less control from a graph point of view and would return a non-symbolic tensor. It would be interesting to see the performance comparison of each.

TensorFlow 2.0 (still in alpha) is eager by default, but still allows for 1.X code to be run, i.e.
```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
I am unfamiliar of other graph-based (symbolic) algebra/machine learning libraries that would be of interest with TensorLy, do you have any in mind? A graph version of TensorLy may be the best way to introduce this backend. Do you think it would be better as its own package or as something under `contrib`?

**Comment by craymichael** [comment]
Apologize for the radio silence on this! Thesis took over my life, but I am back to this issue now. I am currently comparing the speed of graph-based TensorFlow and eager TensorFlow to see if it would be worthwhile to pursue this endeavor. TensorFlow 2.0 is advertised as not losing any speed compared to graph mode, but I'll see how this holds up for this use case. Get back to you hopefully today

**Comment by craymichael** [comment]
Ok, from my tests, TensorFlow graph mode is ~18.9% faster on my system than Eager with 4-way Tensors of 8,000 elements. I used a constant number of iterations without tolerance with random normal elements. I observed almost the same speed up with 4-way 80,000 element tensors. I did not sweep over different modes, huge and small sizes, etc., but eager should and will be slower than graph-based TensorFlow as it is normal TensorFlow but with added overhead (e.g. using `tf.function` to convert python code (JIT) or by not evaluating Tensors in batches, such as when the actual values are needed). When tensors become huge, the difference won't be as noticeable. Another reason I can think of to support graph-based TensorFlow is to support code that is written in graph mode. Requiring all users to use Eager mode will not be compatible with existing codebases, although the future default of TensorFlow is eager mode. Thoughts?

**Comment by JeanKossaifi** [comment]
I completely agree. In fact I have some local versions using graph, e.g. with MXNet.
However I do not see a way to include this in TensorLy in a transparent way.
I guess we could have a graph based version of TensorLy but this involves maintaining a duplicated code base..

**Comment by craymichael** [comment]
I fooled around with some ideas this afternoon and there is not a clear-cut way to support both with a single codebase, unless all code conforms to a graph-compatible format. For example, the TensorFlow API could be mimicked for all backends, introducing functions including `print`, `cond` (if/then/else), and `while`, which will be more work and introduce (minimal) overhead to eager backends. All conditions would need to be converted to functions, etc. 

Another idea I have is to split the overlapping functions into a separate file (e.g. for Tucker, the initialization, loop exit conditions, and factor matrix & core tensor update), then have another two files; one for the eager implementation and another for the graph-based implementation. Each backend would have to be registered with some sort of `is_graph` or `is_eager` attribute. Unless, if we don't require that the API be identical for eager/graph modes, the API can require explicit selection of the graph API. I think avoiding duplicate code is a must

**Comment by JeanKossaifi** [comment]
What about creating another repository, within the TensorLy organisation, that would depend on tensorly and specialize it for tensorflow in graph mode where needed? Or even, more ambitiously, mirror the backend system and specialize tensorly for symbolic execution?

**Comment by craymichael** [comment]
I think I like the idea more so of splitting into a separate repository under the same organization. The more ambitious approach would somewhat duplicate code, no? The internal loop logic of a lot of the decomposition methods can already be treated as symbolic, while the conditionals, variable-length data structures, and some shape-checking is mostly incompatible as-is. The compatible/overlapping code could be kept as its own repository, or at least be kept in their own functions/files within TensorLy and be imported by the symbolic version..

My last sentence sort of sounds like your first idea - do you mind clarifying what you mean by mirroring? Like develop on top of an up-to-date carbon copy of TensorLy and replace what needs to be replaced?

**Comment by JeanKossaifi** [comment]
By mirroring of the backend I meant having a backend as well in the new repository so the symbolic execution is not tensorflow specific but could also be used by e.g. MXnet, etc.

However, to start at least, it might be easier to focus only on TensorFlow I guess.
I am not sure how easy it is to wrap tensorly to enable symbolic execution? 

The other question is, can we do this automatically in some cases, e.g. with ONNX?

> I think I like the idea more so of splitting into a separate repository under the same organization. 

So we create a new repo where we adapt it for tensorflow?

**Comment by craymichael** [comment]
> By mirroring of the backend I meant having a backend as well in the new repository so the symbolic execution is not tensorflow specific but could also be used by e.g. MXnet, etc.

Oh I see, yes that would ultimately be preferable. However, starting with TensorFlow only then abstracting the implementation to multiple frameworks may end up being easier.

I am not too familiar with ONNX, but that is worth exploring before anything is implemented. I am also unsure if ONNX adds overhead or not, or just during model conversion. 

Yes, a new repo would be best at first IMO. But, I think before any action is taken, we should consider ways of reducing duplicate code between the repositories.

FYI, I will be moving early next week and may be unavailable during that time, but I will try to stay as active as I can in this issue.

**Comment by JeanKossaifi** [comment]
Is this still active or should we close?

**Comment by craymichael** [comment]
This can be closed - I don't have the bandwidth for this feature anymore.
