### ISSUE TITLE
Multiplication of two-dimensional and three-dimensional tensors

### ISSUE THREAD

**Issue by goljx** [tensorly/tensorly#111]
There is a two dimensional tensor a[m,n], and a three dimensional tensor b[k,n,h]. What API should I use to multiply two dimensional tensors by three dimensional tensors to get a three dimensional tensor c[k,m,h] ?
Actually I can got it by:

import tensorflow as tf
import tensorly as tl
x=tf.constant([[[1,2],[3,7],[8,9]],
              [[4,5],[6,10],[11,12]]],tf.float32)
a=tf.constant([[-0.70711,0.57735],
             [0.0000,0.57735],
              [0.70711,0.57735]])
reshape_A = tf.reshape(x, [2,6])

re = tf.reshape( tf.matmul(a, reshape_A), [3, 3, 2])

with tf.Session() as sess:
    print(sess.run(re))
    re=re.eval()

But is there an easier way?

**Comment by JeanKossaifi** [comment]
You can use [tensorly.tenalg.contract](http://tensorly.org/dev/modules/generated/tensorly.tenalg.contract.html#tensorly.tenalg.contract). For your example:

```python
import tensorly as tl
import numpy as np
tl.set_backend('tensorflow')

k = 2; m = 3; n = 5; h = 4

A = tl.tensor(np.random.random((m, n)))
B = tl.tensor(np.random.random((k, n, h)))

res = tl.tenalg.contract(A, 1, B, 1)
```
