### ISSUE TITLE
More efficient way to unfold big tensor

### ISSUE THREAD

**Issue by phonchi** [tensorly/tensorly#112]
Dear developers:

I am trying to do HOSVD on a large image dataset. The dataset is arranged as (n_image, height, width ). The size of dataset is very large to about 40-50GB.

To my understanding, I need to first perform unfolding using tensorly.unfold on mode-1/mode-2 and then apply SVD on the unfolding tensors. However, I found that unfolding of mode-1 takes much longer time than mode-2 which may due to copying the data with reshaping as describe [here](https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays).

I wonder if there is a more efficient way to unfold the tensor or even performs HOSVD without unfolding on such big dataset? Thanks in advance!

**Comment by JeanKossaifi** [comment]
I already redefined unfolding to be faster using C ordering of the elements (see my blog post [here](http://jeankossaifi.com/blog/unfolding.html)).
Short of bypassing completely unfolding I do not think there is any easy way to do this faster (HO-SVD, by definition consists in applying SVD to each unfolding). 

You may want to look at [Tucker decomposition](http://tensorly.org/stable/modules/generated/tensorly.decomposition.tucker.html#tensorly.decomposition.tucker), and set up the flag `init='random'`.

**Comment by phonchi** [comment]
Thanks!!
