### ISSUE TITLE
Error: Too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by zhuyf8899** [tensorly/tensorly#113]
Hi, @JeanKossaifi 

When I was using your latest  version (0.4.4) installed from the github website, an error occurs which provides the following error messages:
`
13 sparse_factors = sparse_parafac(tensor=dataset['source_tensor'], rank=5, init='random', random_state=123456, return_errors=True, mask=dataset['mask_tensor'])
     14 print(time.time() - t)

e:\code\opensourcetools\tensorly-master\tensorly\contrib\sparse\core.py in inner(*args, **kwargs)
      8     def inner(*args, **kwargs):
      9         with sparse_context():
---> 10             return func(*args, **kwargs)
     11 
     12     return inner

e:\code\opensourcetools\tensorly-master\tensorly\decomposition\candecomp_parafac.py in parafac(tensor, rank, n_iter_max, init, svd, normalize_factors, tol, orthogonalise, random_state, verbose, return_errors, non_negative, mask)
    177             if mask is not None:
    178                 #tensor = tensor*mask + tl.kruskal_to_tensor(factors, mask=1-mask)
--> 179                 tensor = tensor*mask + tl.kruskal_to_tensor(factors)
    180 
    181             mttkrp = unfolding_dot_khatri_rao(tensor, (weights, factors), mode)

e:\code\opensourcetools\tensorly-master\tensorly\kruskal_tensor.py in kruskal_to_tensor(kruskal_tensor)
    175 
    176     """
--> 177     shape, _ = _validate_kruskal_tensor(kruskal_tensor)
    178     weights, factors = kruskal_tensor
    179 

e:\code\opensourcetools\tensorly-master\tensorly\kruskal_tensor.py in _validate_kruskal_tensor(kruskal_tensor)
     71         return kruskal_tensor.shape, kruskal_tensor.rank
     72 
---> 73     weights, factors = kruskal_tensor
     74 
     75     if len(factors) < 2:

ValueError: too many values to unpack (expected 2)
`

So I check the code in the tensorly/kruskal_tensor.py, found problem in line 73:
weights, factors = kruskal_tensor

It seems strange, could you check it and let me know how to fix it?
Thanks a lot in front.

ZhuYifan

**Comment by JeanKossaifi** [comment]
Thanks for reporting, I'll have a look!

**Comment by zhuyf8899** [comment]
Sorry for disturb again, i found this error when the time I was trying to use CP decomposition with missing data according to the document [(Link)](http://tensorly.org/dev/user_guide/sparse_backend.html).

I think it may help you to locate the problem...

**Comment by zhuyf8899** [comment]
> Thanks for reporting, I'll have a look!

Sorry for disturb again, i found this error when the time I was trying to use CP decomposition with missing data according to the document ([Link](http://tensorly.org/dev/user_guide/sparse_backend.html)).

I think it may help you to locate the problem...

**Comment by JeanKossaifi** [comment]
The error is due to the fact that now kruskal_tensors are expected, which are tuples (weights, factors) rather than just a list of factors.

I updated the doc, do you still have the issue? 
If so can you post minimal code to reproduce the issue?

**Comment by zhuyf8899** [comment]
@JeanKossaifi 
Thanks a lot, I have read the updated doc, the problem has been fixed.
