### ISSUE TITLE
Sparse Tensor Tucker

### ISSUE THREAD

**Issue by simo1000k** [tensorly/tensorly#115]
How can I create a sparse tensor to run the tucker?

Thanks you

**Comment by JeanKossaifi** [comment]
Simply wrap a sparse tensor (e.g. `sparse.random` or `sparse.COO`) in a tensorly tensor. 
You can have a look at the [user guide](http://tensorly.org/dev/user_guide/sparse_backend.html).

**Comment by simo1000k** [comment]
When I run this code :
from tensorly.contrib.sparse.decomposition import tucker
values = []
coords = []
coords.append([0,0])
coords.append([1,2])

values.append([1.0])
values.append([2.0])

coords = np.array(coords, dtype=np.int)
values = np.array(values, dtype=np.float)
p = sparse.COO(coords=coords.T, data=values)

core, factors = tucker(p, ranks=[2,2])
print(core, factors)

![tucker_cat](https://user-images.githubusercontent.com/51096988/60269667-337dd100-98ef-11e9-98e5-7fe4aac3392c.PNG)

**Comment by simo1000k** [comment]
When I run this: 
from tensorly.contrib.sparse.decomposition import tucker
from tensorly.contrib.sparse import tensor
values = []
coords = []
coords.append([0,0])
coords.append([1,2])

values.append([1.0])
values.append([2.0])

coords = np.array(coords, dtype=np.int)
values = np.array(values, dtype=np.float)
p = sparse.COO(coords=coords.T, data=values)
X = tensor(p)

core, factors = tucker(X, ranks=[2,2])
print(core, factors)

I got this error: 
![tucker_cat](https://user-images.githubusercontent.com/51096988/60270591-07634f80-98f1-11e9-89e1-b8c2e84f6a56.PNG)

**Comment by simo1000k** [comment]
When I run this:
from tensorly.contrib.sparse.decomposition import tucker
from tensorly.contrib.sparse import tensor
values = []
coords = []
coords.append([0,0])
coords.append([1,2])

values.append([1.0])
values.append([2.0])

coords = np.array(coords, dtype=np.int)
values = np.array(values, dtype=np.float)
p = sparse.COO(coords=coords.T, data=values)
X = tensor(p)

core, factors = tucker(X, ranks=[2,2])
print(core, factors)

I got this error:



Il giorno gio 27 giu 2019 alle ore 15:16 Jean Kossaifi <
notifications@github.com> ha scritto:

**Comment by JeanKossaifi** [comment]
The problem seems to be the way you are creating the sparse array. I recommend you check directly the sparse documentation. One of the issues seems to be that you are using numpy dtypes, not sparse dtypes.

The following code works fine:
```python
import numpy as np
import sparse
import tensorly.contrib.sparse as tl
from tensorly.contrib.sparse.decomposition import tucker
X = sparse.COO(np.arange(24).reshape((3, 4, 2)))
X = sparse.COO(X.coords, X.data, shape=(100, 100, 100))
X = tl.tensor(X, dtype=tl.float32)
core, factors = tucker(X, rank=[2,2,2])
```

**Comment by simo1000k** [comment]
Thanks for the reply!
When I write your code, I got this warning on "tl.float32" :  Cannot find reference 'float32' in '__init_py'

**Comment by simo1000k** [comment]
Thanks a lot!

**Comment by simo1000k** [comment]
Thanks you for the reply!
When I write your code, I got this error on "tl.float32" : Cannot find reference 'float32' in '__init_.py'

**Comment by JeanKossaifi** [comment]
There should not be any _init.py file.
Where are you running this? Could there be a collision with your local files?
Also, are you running the latest version of TensorLy (master)?

**Comment by simo1000k** [comment]
I'd try to install this with pip : pip install -U tensorly
and in this way: 
git clone https://github.com/tensorly/tensorly
cd tensorly
pip install -e 

but I got the same error 

I don't know if there is a new version of Tensorly

**Comment by simo1000k** [comment]
What can I do?

**Comment by JeanKossaifi** [comment]
The version from git is the latest one.

Can you print the result of `import tensorly; tensorly.__version__`? 
You are using Python 3, right?

What do error do you get when you run:
```python
import numpy as np
import sparse
import tensorly.contrib.sparse as tl
from tensorly.contrib.sparse.decomposition import tucker
X = sparse.COO(np.arange(24).reshape((3, 4, 2)))
X = sparse.COO(X.coords, X.data, shape=(100, 100, 100))
X = tl.tensor(X, dtype=tl.float32)
core, factors = tucker(X, rank=[2,2,2])
```

**Comment by simo1000k** [comment]
Tensorly version is : 0.4.4
Python 3.7
I got this error on "tl.float32" : Cannot find reference 'float32' in '_init.py' without run the code 
When I run that code I haven't error, but if I change rank to 3 or 4, I have this error:
![ccc](https://user-images.githubusercontent.com/51096988/60344237-6212af00-99b6-11e9-997c-181dd470e5dc.PNG)

**Comment by simo1000k** [comment]
Also I try to create another tensor in this way:
import sparse
import tensorly.contrib.sparse as tl
from tensorly.contrib.sparse.decomposition import tucker

coords = [[0, 1, 2, 3, 4],[0, 2, 2, 3, 4], [0, 3, 2, 3, 4]]
data = [10, 20, 30, 40, 50]
s = sparse.COO(coords, data, shape=(5, 5, 5))
print(s.todense())
X = tl.tensor(s, dtype=tl.float32)

core, factors = tucker(s, ranks=[4,4,4])

but I got another error : ValueError: matrix type must be 'f', 'd', 'F', or 'D'


How I can do it?
