### ISSUE TITLE
Pip pkg not updated

### ISSUE THREAD

**Issue by santimar** [tensorly/tensorly#117]
I installed Tensorly via Pip and the latest release is 0.4.3 released on 25 Dec 2018.

I performed a non negative tucker decomposition but I got this error:

> Traceback (most recent call last):
  File "[...]/myscript.py", line 190, in <module>
    core, factors = non_negative_tucker(tensor, rank=3)
  File "[...]\tensorly\decomposition\_tucker.py", line 192, in non_negative_tucker
    message = "Given only one int for 'rank' intead of a list of {} modes. Using this rank for all modes.".format(len(modes))
NameError: name 'modes' is not defined

This error seems to have been fixed in https://github.com/tensorly/tensorly/commit/5ec54f47d56515eca3d28ae3826462433dd95ccb#diff-4c9b88d6e57e1896595cf9edeb40a2f6 on 18 April
In fact, by installing Tensorly by cloning this repo, the same code works ( I got a warning on the fact that I passed an int instead of a vector of 3 int, but the function signature require just an int)

Did you just forget to make a new release?

**Comment by JeanKossaifi** [comment]
Yes, I am waiting for a few more features to be merged and some more tests added before make a release, but will make one soon.

In the mean time you can install directly from source to fix the issue.
Let me know if you have any issue in doing so.

**Comment by JeanKossaifi** [comment]
0.4.4 was released. Release is now done automatically with Travis.
