### ISSUE TITLE
something looks going wrong when used the  non_negative_tucker decomposition

### ISSUE THREAD

**Issue by simonZlz** [tensorly/tensorly#118]
I want to use non_negative_tucker to decomposite the 4-order tensor,and then use the core and factors tensors to reconstruct the 4-order tensor for recovering the missing value .But  the last column of the reconstruction data  is always very small. I don't know how to solve this problem.
this is the initial data:
![image](https://user-images.githubusercontent.com/40993207/61168786-ac368b80-a585-11e9-86fc-ddf303295fe8.png)
this is the reconstruction data:
![image](https://user-images.githubusercontent.com/40993207/61168791-d0926800-a585-11e9-843a-817e9f6a8be9.png)
I would appreciate it very much if someone could help me solve this problem.

**Comment by JeanKossaifi** [comment]
Did you manage to get the results you were expecting?

**Comment by simonZlz** [comment]
> Did you manage to get the results you were expecting?

yeah,I found I have mistoken a viariable in my program . thanks for replying！
