### ISSUE TITLE
Non_Negative_Parafac non-start error

### ISSUE THREAD

**Issue by WesLudwig** [tensorly/tensorly#124]
I'm using the non_negative_parafac function to decompose 3way data tensors of Mass Spectrometry data with approximate dimensions of (15x40x7000). 

The function usually works just fine, but for certain numbers of factors (~13) for certain data tensors, I get an error where the iterations never begin, so I see nothing but the "thinking" asterisk in a Jupyter notebook. I'm running multiple decompositions of each data tensor to see which number of factors provides the best data, so this kind of silent error is a killer for what I'm doing.

This is my first issue post and I can't guess what you'll need, so please let me know what other information you would like to see and I'll provide it asap. 

Thanks for any help!
www.rocklinlab.org

**Comment by JeanKossaifi** [comment]
I am not sure that is happening. Does it happen if you run your code in a script too?
Are you sure it crashes, and is not actually running the SVD for the init? If so you can try  setting `init='random'`.

**Comment by WesLudwig** [comment]
That was exactly it, it was that the SVD wasn't converging quickly for particular cases. Thanks for the help!
