### ISSUE TITLE
Use uarray for backend support rather than self-rolled solution

### ISSUE THREAD

**Issue by hameerabbasi** [tensorly/tensorly#126]
As far as I can tell, Tensorly has a custom-rolled backend solution. We've built a solution that we hope is general enough for Tensorly and other projects while also being a one-stop-shop for backend-dispatch.

The project is called [`uarray`](https://uarray.readthedocs.io/en/latest/), and it's meant to be a general multiple-dispatch and backend-dispatch solution. There's a companion package called [`unumpy`](https://unumpy.readthedocs.io/en/latest/) that aims to make a dispatchable version of NumPy.

This is meant to be a discussion about whether Tensorly maintainers are willing to have this discussion and what it would take for Tensorly to adopt `uarray`/`unumpy` as its preferred backend system.

**Comment by JeanKossaifi** [comment]
You guys have been instrumental in refactoring the backend to its current form and it seems it is quite similar to the concepts behind uarray (dispatching, etc).

On principle I am happy to explore using it, provided that it is stable, lightweight and doesn't add undue hidden complexity / dependencies -- I can also to try and help with development.

One side note: in TensorLy we don't really need the context manager much (the only case now being for sparse support). In general I like to separate the context manager (e.g. `with backend_context(backend)`) from the actual setter (e.g. `set_backend(backend)`).

**Comment by hameerabbasi** [comment]
> You guys have been instrumental in refactoring the backend to its current form and it seems it is quite similar to the concepts behind uarray (dispatching, etc).

Thanks for the warm message!

> On principle I am happy to explore using it, provided that it is stable, lightweight and doesn't add undue hidden complexity / dependencies -- I can also to try and help with development.

There are build-time dependencies, but we have wheels for all major platforms. The dependency tree would go `uarray` -> `unumpy` -> TensorLy. You might be more interested in `unumpy`, which is the backend system for NumPy-like libraries.

> One side note: in TensorLy we don't really need the context manager much (the only case now being for sparse support). In general I like to separate the context manager (e.g. with backend_context(backend)) from the actual setter (e.g. set_backend(backend)).

`set_backend` is the context manager, `set_global_backend` is the setter, so we do separate them, of course you can wrap them and call them something different if you feel like it.

**Comment by JeanKossaifi** [comment]
Hi - sorry for the long delay - I am working on this again!
I had a look at unumpy, it looks great! I'd be happy to help/contribute there too as needed.

How would we go about using it here? 

I am also looking into adding a similar backend system but for the tensor algebra module. There, the idea is not only to have actual backends (e.g. numpy, pytorch etc) implement directly the routines, but also to enable different implementations of the same function (e.g. one for speed, one for memory efficiency, etc). It seems like the dispatching mechanism would be a clean way to achieve that (e.g. each approach could be a different backend when available?). What do you think?

**Comment by hameerabbasi** [comment]
> Hi - sorry for the long delay - I am working on this again!

No issues, glad to hear that!

> I had a look at unumpy, it looks great! I'd be happy to help/contribute there too as needed.
> I noticed that `array_module` ([NEP 37](https://numpy.org/neps/nep-0037-array-module.html) ) now replace `array_function`?

That is what is proposed, but we had a meeting and it was decided not to remove `__array_function__` and instead keep it. `__array_module__` is a work in progress, it isn't in NumPy yet.

> How would we go about using it here?

You can't yet...

> I am also looking into adding a similar backend system but for the tensor algebra module. There, the idea is not only to have actual backends (e.g. numpy, pytorch etc) implement directly the routines, but also to enable different implementations of the same function (e.g. one for speed, one for memory efficiency, etc). It seems like the dispatching mechanism would be a clean way to achieve that (e.g. each approach could be a different backend when available?). What do you think?

`uarray` can help you with that! It supports nested backends. The end-user API would look like the following:

```python
with ua.set_backend(tensorly_speed_backend), ua.set_backend(dask_backend)
    # Code here
```

If you like, we could set up a call discussing this!

**Comment by JeanKossaifi** [comment]
> > How would we go about using it here?
> 
> You can't yet...

I meant using uarray/unumpy within TensorLy, not using the `__array_module__`. Do you think the transition from `__array_function__` to `__array_module__` will break a lot of things?

> If you like, we could set up a call discussing this!

That would be great, feel free to drop me an email! :)

> with ua.set_backend(tensorly_speed_backend)

I was thinking exactly something like this, perhaps specific to the case, e.g. 

```python
with tl.set_tenalg_backend('speed'):
    # Code here
```

**Comment by aarmey** [comment]
I am not seeing activity from `unumpy` over the last two years, so I am not sure how active this is anymore. Luckily, the backends have simplified over time as projects have unified around numpy interfaces.
