### ISSUE TITLE
MemoryError on non-negative Tucker decomposition

### ISSUE THREAD

**Issue by santimar** [tensorly/tensorly#136]
#### Describe the bug
I got a MemoryError (even if I had 3GB of free ram) while I was trying to make a non negative tucker decomposition on a 3D tensor.
After some debugging I found that the problem seems to be the SVD initialization, in fact by changing ``` init='svd'``` with ``` init='random'``` I got no error.

Also, this exception only appears if I try to decompose with `rank > same dimension of the tensor` on "big" tensor

For instance:
With a 1000 x 1000 x 5 tensor
`non_negative_tucker(X, rank=[400, 300, 5], init='svd')` works
`non_negative_tucker(X, rank=[400, 300, 6], init='svd')` doesn't work
`non_negative_tucker(X, rank=[400, 300, 6], init='random')` works

With a 100 x 100 x 5 tensor
`non_negative_tucker(X, rank=[40, 30, 5], init='svd')` works
`non_negative_tucker(X, rank=[40, 30, 10], init='svd')` works
`non_negative_tucker(X, rank=[40, 30, 10], init='random')` works

With a 1000 x 5 x 1000 tensor
`non_negative_tucker(X, rank=[10, 5, 10], init='svd')` works
`non_negative_tucker(X, rank=[10, 6, 10], init='svd')` doesn't work
`non_negative_tucker(X, rank=[10, 6, 10], init='random')` works
#### Steps or Code to Reproduce

```python
import tensorly as tl
import numpy as np
from tensorly.decomposition import non_negative_tucker

X = tl.tensor(np.random.rand(1000, 1000, 5), dtype=np.float32)
rank = 6
core, factors = non_negative_tucker(X, rank=[rank, rank, rank], init='svd')

```

#### Actual result

```
Traceback (most recent call last):
  File "[...]/scratch_3.py", line 7, in <module>
    core, factors = non_negative_tucker(X, rank=[400, 300, 6], init='svd')
  File "[...]\tensorly\decomposition\_tucker.py", line 203, in non_negative_tucker
    core, factors = tucker(tensor, rank)
  File "[...]\tensorly\decomposition\_tucker.py", line 149, in tucker
    svd=svd, tol=tol, random_state=random_state, verbose=verbose)
  File "[...]\tensorly\decomposition\_tucker.py", line 74, in partial_tucker
    eigenvecs, _, _ = svd_fun(unfold(tensor, mode), n_eigenvecs=rank[index])
  File "[...]\tensorly\backend\core.py", line 695, in partial_svd
    U, S, V = scipy.linalg.svd(matrix, full_matrices=full_matrices)
  File "[...]\scipy\linalg\decomp_svd.py", line 129, in svd
    full_matrices=full_matrices, overwrite_a=overwrite_a)
MemoryError
```

#### Versions

Windows-10-10.0.18362-SP0
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
NumPy 1.16.4
SciPy 1.3.1
TensorLy 0.4.4

**Comment by JeanKossaifi** [comment]
As you noted, the issue is in the numpy SVD. Sparse SVD is fast but if rank > dimension, then you have to do full SVD on a huge unfolding. I will try to have a look when I get a minute see if we can avoid calling svd but I do not think there is an easy fix. Feel free to have a go at it if you wish!

Setting init to 'random' fixes the issue and with a sufficient number of iterations should not impact the error much.

**Comment by santimar** [comment]
I was looking at this: http://fa.bianp.net/blog/2012/singular-value-decomposition-in-scipy/
There are two ways in scipy to calculate the SVD.
You are using the `scipy.linalg.svd` version, which is faster but uses more memory.
There is also the `scipy.sparse.linalg.svds` which works even on dense array, it's slower but uses less memory

**Comment by JeanKossaifi** [comment]
You might want to have a look at the source code of `partial_svd`. I already use a sparse decomposition when the rank is < than min(matrix.shape). If you try running `scipy.sparse.linalg.svds` on the unfolding of your example tensor, along the last mode, you will see that it fails. In other words, you have a rank higher than the rank of the unfolding. If you set a rank < 6 and it will work without issue.

I will see if there is any way to speed it up in that case but I doubt it, short of using a randomized algorithm. The easiest is to use a randomized init in that case.
