### ISSUE TITLE
Feature Request: Outer Product

### ISSUE THREAD

**Issue by isabaerchen** [tensorly/tensorly#143]
Hi,

I am starting to work with tensors and found your toolbox. When trying the CPD, I first wanted to create a rank-3 tensor and then decompose it again and look at the result, since CPD is unique. There I noticed that no outer vector product is implemented in the toolbox. It would be nice if there is one, for simulations etc.

I know there is numpy.outer, but this only works for 2 vectors.

Thanks in advance,
Isi

**Comment by JeanKossaifi** [comment]
Hi @isabaerchen,
I did add an [outer product](https://github.com/tensorly/tensorly/blob/master/tensorly/tenalg/outer_product.py) in the master branch, it should do what you need.
Let me know if you have any question or issue using it.

**Comment by isabaerchen** [comment]
Thanks a lot, exactly what I needed!
I think to use tenalg.outer, in the init-file the following line is missing: from .outer_product import outer
That's why I couldn't call the function and therefore thought it does not exist (also it is missing in the documentation).

However, kruskal_to_tensor is doing what I was looking for, so I will use that function. :)
