### ISSUE TITLE
tl.unfold does not work on sparse.COO input

### ISSUE THREAD

**Issue by JunhaoWang** [tensorly/tensorly#159]
#### Describe the bug
tl.unfold does not work on sparse.COO input

#### Steps or Code to Reproduce

```python
import sparse
import tensorly as tl
coords = [[0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4]]
data = [10, 20, 30, 40, 50]
s = sparse.COO(coords, data, shape=(5, 5))
tl.unfold(s, 0)
```

#### Expected behavior
should return a 2-D sparse.COO array

#### Actual result

>>> tl.unfold(s, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangjunh/anaconda3/envs/clean5/lib/python3.6/site-packages/tensorly/base.py", line 51, in unfold
    return T.reshape(T.moveaxis(tensor, mode, 0), (tensor.shape[mode], -1))
  File "/home/wangjunh/anaconda3/envs/clean5/lib/python3.6/site-packages/tensorly/backend/__init__.py", line 160, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "<__array_function__ internals>", line 6, in moveaxis
TypeError: no implementation found for 'numpy.moveaxis' on types that implement __array_function__: [<class 'sparse._coo.core.COO'>]

#### Versions

Linux-5.0.0-1031-gcp-x86_64-with-debian-buster-sid
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29)
[GCC 7.3.0]
NumPy 1.18.1
SciPy 1.4.1
TensorLy 0.4.5

**Comment by kharris** [comment]
This issue is closed, but the following code provides a workaround:
```
def unfold(data, mode):
    data = data.copy()
    # first step: swap axis with first
    if mode != 0:
        row_mode = data.coords[mode, :]
        data.coords[mode, :] = data.coords[0, :]
        data.coords[0, :] = row_mode
    # second step: reshape
    return data.reshape((data.shape[mode], -1))
```
