### ISSUE TITLE
segmentation fault when calling parafac() for CP decomposition 

### ISSUE THREAD

**Issue by BichenWuUCB** [tensorly/tensorly#16]
Hi,

I encountered segmentation faults when calling `parafac()` for CP decomposition. My code is the following:
```
import numpy as np
import tensorly as tl
from tensorly.decomposition import parafac

A = tl.tensor(np.random.rand(256, 64, 3, 3))
factor = parafac(A, rank=4)
```

As long as the rank is set larger than 3, it's going to fail. Any suggestions?

**Comment by JeanKossaifi** [comment]
Thanks for flagging! Which backend do you use?

**Comment by BichenWuUCB** [comment]
I'm using MXNET backend.

**Comment by JeanKossaifi** [comment]
Ok, will get back to you soon!

**Comment by JeanKossaifi** [comment]
I had no issue with this, you're issue might come from not having enough memory available.
I am working on reducing the memory usage when using MXNet, which might solve your problem!
