### ISSUE TITLE
An equation doesn't hold.

### ISSUE THREAD

**Issue by Haobo1108** [tensorly/tensorly#163]
#### Describe the bug
The highlighted equation doesn't hold for the tucker tensor. For more information, please refer to page 475 of Tensor Decompositions and Applications (2009).
![Capture](https://user-images.githubusercontent.com/42907836/77050901-64fe7580-6a05-11ea-9035-d1ce6f4a9674.PNG)

#### Steps or Code to Reproduce

```python
from tensorly.random import random_tucker
import tensorly as tl
from tensorly.tenalg import kronecker

[core, factors] = random_tucker((4, 4, 4), [2, 3, 2])
tensor = tl.tucker_to_tensor([core, factors])
mode = 1  # The selected mode.
tensor_unfold = tl.unfold(tensor, mode=mode)
core_unfold = tl.unfold(core, mode=mode)
factors_copy = factors.copy()
del factors_copy[mode]
kron = kronecker(factors_copy[::-1])

print(tensor_unfold - factors[mode].dot(core_unfold).dot(kron.T))  # All elements should be zero.
```

#### Expected behavior
The elements in the printing matrix should be zero.

#### Actual result
The elements are significantly not zero.

#### Versions
The backend is NumPy.

**Comment by JeanKossaifi** [comment]
Hi @Haobo1108,

In TensorLy, we use a different [definition of unfolding](http://tensorly.org/dev/user_guide/tensor_basics.html) to allow for better performance with C-ordering of the elements (notably on GPU). I wrote about it in more details in a [blog post](http://jeankossaifi.com/blog/unfolding.html). 
See also the tensorly paper and this [stack-overflow response](https://stackoverflow.com/questions/49970141/using-numpy-reshape-to-perform-3rd-rank-tensor-unfold-operation/50086319#50086319).

In the formula you are looking at, you need to permute the order of the factors in the Kronecker products:

   X[n]= U(n) G[n] ( U(1) ⊗ ⋯ U(n−1) ⊗ U(n+1) ⊗ ⋯ ⊗ U(N) )^T

Will close as there is no issue in the tensorly formula, feel free to reopen if you have more questions.

**Comment by Haobo1108** [comment]
Dear Jean,
Got it! Thanks a lot!
