### ISSUE TITLE
large sparse matrix causing crash during decomposition

### ISSUE THREAD

**Issue by jtliso** [tensorly/tensorly#17]
When I try to use Tucker decomposition of a large sparse matrix, Tensorly crashes. I have used both the MXNet and NumPy backend, and both cause the crash due to memory issues.

The dimensions of my sparse matrix are (358, 556, 2). I was hoping to use Tensorly for even larger sparse matrices. I did not know if you guys intend to release any support for sparse matrices, or if perhaps something I am doing could be incorrect.

**Comment by JeanKossaifi** [comment]
We don't yet have support for sparse tensors but it is on the roadmap!

**Comment by MaxMcGlinnPoole** [comment]
@JeanKossaifi Great to hear it is on the roadmap. I also need this functionality for the project I am working on. Keep up the great work!

**Comment by JeanKossaifi** [comment]
Thanks! We welcome contributions if you are interested to take a crack at it! :)

**Comment by santiago-py-chen** [comment]
Hi, I wonder if it is normal that when I was calling partial_tucker on a given tensor always returning core tensor and factors with the same magnitude but different signs? Even if I fixed the random_state the sign of returned core tensor and factor was still different from time to time.  (Not sure if it should be raised here, I would move it to somewhere else if inappropriate)

**Comment by JeanKossaifi** [comment]
It is the result of the sign indeterminacy of the singular value decomposition. 
See for instance [this article](https://prod.sandia.gov/techlib-noauth/access-control.cgi/2007/076422.pdf) about the problem and a possible solution to it. We can add a SignFlip function and an additional parameter in the decomposition algorithms on whether to use it. 

Feel free to take a crack at it!
