### ISSUE TITLE
Shape mis-match in SVD when min_dim < n_eigenvecs < max_dim

### ISSUE THREAD

**Issue by aarmey** [tensorly/tensorly#176]
First, just to explain why I'm looking at this—I'm interested in implementing a truncated SVD because we deal with data that's very tall and skinny. For example, we're using PARAFAC2 where we end up with a 3591070 x 66 matrix, and this is trying to allocate a 3591070 x 3591070 one (93.8 TiB) for the full SVD.

#### Describe the bug

For SVD calls where min_dim < n_eigenvecs < max_dim, the dimensions of the resulting matrices don't match my expectations.

Ultimately, the root of the problem here seems to be in the size of the matrices returned from `scipy.linalg.svd`, because they clearly don't match [the documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html). However, I want to check that I'm not missing something obvious. Also, the rest of the code in Tensorly seems to depend on these sizes, so it's possible this is right.

#### Steps or Code to Reproduce

I added the following block of assertions to the end of `partial_svd()` in core.py and ran the tests.

```python
assert U.shape[0] == matrix.shape[0]
assert U.shape[1] == n_eigenvecs
assert S.shape[0] == n_eigenvecs
assert V.shape[0] == n_eigenvecs
assert V.shape[1] == matrix.shape[1]
```

#### Expected behavior

These should pass. Specifically, in the two cases below, I'd expect U, S, V of:

- 3x3, 3, and 3x8 for `test_parafac`
- 4x2, 2, and 2x2 for `test_tucker`

#### Actual result

This fails in two places:

First, in `test_parafac`, `partial_svd()` gets called with a 3x8 matrix and `n_eigenvecs = 4`. This leads to U, S, V of 3x3, 3, and 4x8 respectively.

Second, in `test_tucker`, `partial_svd()` gets called with a 4x2 matrix and `n_eigenvecs = 3`. This leads to U, S, V of 4x3, 2, and 2x2 respectively.

#### Versions

This is with Python v3.8, NumPy 1.18.5, and scipy 1.4.1.

**Comment by aarmey** [comment]
Never mind... think I found an explanation for this.

**Comment by JeanKossaifi** [comment]
What was the issue?

**Comment by aarmey** [comment]
I wasn't following that `partial_svd()` needs the full, not reduced, SVD. Taking that into account these sizes make sense. The explanation in #136 was helpful.

I would be interested in more scalable SVD implementations as I've been hitting memory errors, and the SVD initialization seems to do much better than random for my PARAFAC2 application. I was thinking maybe even getting the reduced SVD with `full_matrix=False`, and then padding up to the right size with random vectors, but that would be a terrible hack.

**Comment by JeanKossaifi** [comment]
`partial_svd` _should_ use (Scipy's) sparse SVD when the rank is smaller than the smallest dimension, rather than the full SVD.
I will try to find some time to add a randomized SVD, this should help for large scale experiments.
