### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by jiyuwangbupt** [tensorly/tensorly#178]

**Comment by JeanKossaifi** [comment]
You didn't fill the issue: what is your error/question?

**Comment by jiyuwangbupt** [comment]
When I performed Tucker decomposition on the mnist image data, I reported the above error.ValueError: array must not contain infs or NaNs. The relevant code is as follows：
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import numpy as np
import tensorly as tl
from tensorly.decomposition import tucker
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

from tensorflow.examples.tutorials.mnist import input_data
# number 1 to 10 data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

for i in range(1000):
    mnist_x, mnist_y = mnist.train.next_batch(64)
    x_test, y_test = mnist.test.next_batch(64)
    mnist_x = mnist_x.reshape([-1, 28, 28])
    x_test = x_test.reshape([-1, 28, 28])
    batch=64
    newtrain = []
    # print("weidu2",x_test[0].shape)
    # print("weidu3",x_test[0])
    newtest = []
    for j in range(batch):
        newlamutaAtrain, newfactortrain = tucker(mnist_x[j], rank=[20, 20])
        newlamutaAtest, newfactortest = tucker(x_test[j], rank=[20, 20])
        newtrain.append(newlamutaAtrain)
        newtest.append(newlamutaAtest)
    newtrain = np.array(newtrain).reshape(batch, 20* 20)
    newtest = np.array(newtest).reshape(batch, 20 * 20)
    sess.run(train_step, feed_dict={xs: newtrain, ys: mnist_y, keep_prob: 0.5})
    if i % 50 == 0:
        print(compute_accuracy(
            newtest , y_test))


The versions are as follows:
Windows-10-10.0.18362-SP0
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
NumPy 1.18.1
SciPy 1.4.1
Using numpy backend.
TensorLy 0.4.3

**Comment by jiyuwangbupt** [comment]
An error occurred in this line.
newlamutaAtrain, newfactortrain = tucker(mnist_x[j], rank=[20, 20])

**Comment by JeanKossaifi** [comment]
Thanks @jiyuwangbupt  -- can you post a minimal piece of code to reproduce your issue?

Why are you disabling v2_behavior in tensorflow? If your tensors are all in tensorflow you also need to set the backend:
```python
tl.set_backend('tensorflow')
```
Are your mnist samples in float32 or uint8?

Generally, what are you trying to achieve? Currently you  are factorizing 2D images using Tucker, so you may as well do an SVD. Also, since you have a batch of images, you could factorize them jointly using `partial_tucker`.

**Comment by jiyuwangbupt** [comment]
Thanks@JeanKossaifi. Since my tensorflow version is 2.0, and then the code is tensorflow1.0 version code, so I used 
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior().
mnist samples are in numpy.float32. I just want to try to use tensor decomposition on the input data and operate on the factor matrices or core tensor after the tensor decomposition.
 Therefore I don't need to set:
tl.set_backend('tensorflow')
I just simply use the numpy backend. Maybe there are too many zeros in the mnist data that caused the error?
The code are as follows, I have not modified the original placeholder.

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import numpy as np
import tensorly as tl
from tensorly.decomposition import tucker
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

from tensorflow.examples.tutorials.mnist import input_data
# number 1 to 10 data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

def compute_accuracy(v_xs, v_ys):
    global prediction
    y_pre = sess.run(prediction, feed_dict={xs: v_xs, keep_prob: 1})
    correct_prediction = tf.equal(tf.argmax(y_pre ,1), tf.argmax(v_ys ,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    result = sess.run(accuracy, feed_dict={xs: v_xs, ys: v_ys, keep_prob: 1})
    return result

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
    # stride [1, x_movement, y_movement, 1]
    # Must have strides[0] = strides[3] = 1
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
    # stride [1, x_movement, y_movement, 1]
    return tf.nn.max_pool(x, ksize=[1 ,2 ,2 ,1], strides=[1 ,2 ,2 ,1], padding='SAME')

# define placeholder for inputs to network
xs = tf.placeholder(tf.float32, [None, 784]) # 28x28
ys = tf.placeholder(tf.float32, [None, 10])
keep_prob = tf.placeholder(tf.float32)
x_image = tf.reshape(xs, [-1, 20, 20, 1])
print(x_image)  # [n_samples, 28,28,1]

## conv1 layer ##
W_conv1 = weight_variable([5 ,5, 1 ,32]) # patch 5x5, in size 1, out size 32
b_conv1 = bias_variable([32])
h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1) # output size 28x28x32
h_pool1 = max_pool_2x2(h_conv1)                                         # output size 14x14x32

## conv2 layer ##
W_conv2 = weight_variable([5 ,5, 32, 64]) # patch 5x5, in size 32, out size 64
b_conv2 = bias_variable([64])
h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2) # output size 14x14x64
h_pool2 = max_pool_2x2(h_conv2)                                         # output size 7x7x64

## func1 layer ##
W_fc1 = weight_variable([ 5 * 5 *64, 1024])
b_fc1 = bias_variable([1024])
# [n_samples, 7, 7, 64] ->> [n_samples, 7*7*64]
h_pool2_flat = tf.reshape(h_pool2, [-1, 5* 5 * 64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

## func2 layer ##
W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])
prediction = tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2) + b_fc2)

# the error between prediction and real data
cross_entropy = tf.reduce_mean(-tf.reduce_sum(ys * tf.log(prediction),
                                              reduction_indices=[1]))  # loss
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

sess = tf.InteractiveSession()
# important step
sess.run(tf.global_variables_initializer())

for i in range(1000):
    mnist_x, mnist_y = mnist.train.next_batch(64)
    x_test, y_test = mnist.test.next_batch(64)
    # print(type(mnist_x))
    mnist_x = mnist_x.reshape([-1, 28, 28]).astype(np.float32)
    x_test = x_test.reshape([-1, 28, 28]).astype(np.float32)
    batch=64
    newtrain = []
    # print("weidu2",x_test[0].shape)
    # print("weidu3",x_test[0])
    newtest = []
    for j in range(batch):
        newlamutaAtrain, newfactortrain = tucker(mnist_x[j], rank=[20, 20])
        newlamutaAtest, newfactortest = tucker(x_test[j], rank=[20, 20])
        newtrain.append(newlamutaAtrain)
        newtest.append(newlamutaAtest)
    newtrain = np.array(newtrain).reshape(batch, 20* 20)
    newtest = np.array(newtest).reshape(batch, 20 * 20)
    sess.run(train_step, feed_dict={xs: newtrain, ys: mnist_y, keep_prob: 0.5})
    if i % 50 == 0:
        print(compute_accuracy(
            newtest , y_test))

**Comment by jiyuwangbupt** [comment]
Thanks@JeanKossaifi. Since my tensorflow version is 2.0, and then the code is tensorflow1.0 version code, so I used
 import tensorflow.compat.v1 as tf
 tf.disable_v2_behavior().
 mnist samples are in numpy.float32. I just want to try to use tensor decomposition on the input data and operate on the factor matrices or core tensor after the tensor decomposition.
 Therefore I don't need to set:
 tl.set_backend('tensorflow')
 I just simply use the numpy backend. Maybe there are too many zeros in the mnist data that caused the error?
 The code are as follows, I have not modified the original placeholder.

import os
 os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
 import numpy as np
 import tensorly as tl
 from tensorly.decomposition import tucker
 import tensorflow.compat.v1 as tf
 tf.disable_v2_behavior()

from tensorflow.examples.tutorials.mnist import input_data

number 1 to 10 data

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

def compute_accuracy(v_xs, v_ys):
 global prediction
 y_pre = sess.run(prediction, feed_dict={xs: v_xs, keep_prob: 1})
 correct_prediction = tf.equal(tf.argmax(y_pre ,1), tf.argmax(v_ys ,1))
 accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
 result = sess.run(accuracy, feed_dict={xs: v_xs, ys: v_ys, keep_prob: 1})
 return result

def weight_variable(shape):
 initial = tf.truncated_normal(shape, stddev=0.1)
 return tf.Variable(initial)

def bias_variable(shape):
 initial = tf.constant(0.1, shape=shape)
 return tf.Variable(initial)

def conv2d(x, W):
 # stride [1, x_movement, y_movement, 1]
 # Must have strides[0] = strides[3] = 1
 return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
 # stride [1, x_movement, y_movement, 1]
 return tf.nn.max_pool(x, ksize=[1 ,2 ,2 ,1], strides=[1 ,2 ,2 ,1], padding='SAME')

define placeholder for inputs to network

xs = tf.placeholder(tf.float32, [None, 784]) # 28x28
 ys = tf.placeholder(tf.float32, [None, 10])
 keep_prob = tf.placeholder(tf.float32)
 x_image = tf.reshape(xs, [-1, 20, 20, 1])
 print(x_image)  # [n_samples, 28,28,1]

conv1 layer

W_conv1 = weight_variable([5 ,5, 1 ,32]) # patch 5x5, in size 1, out size 32
 b_conv1 = bias_variable([32])
 h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1) # output size 28x28x32
 h_pool1 = max_pool_2x2(h_conv1)                                         # output size 14x14x32

conv2 layer

W_conv2 = weight_variable([5 ,5, 32, 64]) # patch 5x5, in size 32, out size 64
 b_conv2 = bias_variable([64])
 h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2) # output size 14x14x64
 h_pool2 = max_pool_2x2(h_conv2)                                         # output size 7x7x64

func1 layer

W_fc1 = weight_variable([ 5 * 5 *64, 1024])
 b_fc1 = bias_variable([1024])

[n_samples, 7, 7, 64] -&gt;&gt; [n_samples, 7764]

h_pool2_flat = tf.reshape(h_pool2, [-1, 5* 5 * 64])
 h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)
 h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

func2 layer

W_fc2 = weight_variable([1024, 10])
 b_fc2 = bias_variable([10])
 prediction = tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2) + b_fc2)

the error between prediction and real data

cross_entropy = tf.reduce_mean(-tf.reduce_sum(ys * tf.log(prediction),
 reduction_indices=[1]))  # loss
 train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

sess = tf.InteractiveSession()

important step

sess.run(tf.global_variables_initializer())

for i in range(1000):
 mnist_x, mnist_y = mnist.train.next_batch(64)
 x_test, y_test = mnist.test.next_batch(64)
 # print(type(mnist_x))
 mnist_x = mnist_x.reshape([-1, 28, 28]).astype(np.float32)
 x_test = x_test.reshape([-1, 28, 28]).astype(np.float32)
 batch=64
 newtrain = []
 # print("weidu2",x_test[0].shape)
 # print("weidu3",x_test[0])
 newtest = []
 for j in range(batch):
 newlamutaAtrain, newfactortrain = tucker(mnist_x[j], rank=[20, 20])
 newlamutaAtest, newfactortest = tucker(x_test[j], rank=[20, 20])
 newtrain.append(newlamutaAtrain)
 newtest.append(newlamutaAtest)
 newtrain = np.array(newtrain).reshape(batch, 20* 20)
 newtest = np.array(newtest).reshape(batch, 20 * 20)
 sess.run(train_step, feed_dict={xs: newtrain, ys: mnist_y, keep_prob: 0.5})
 if i % 50 == 0:
 print(compute_accuracy(
 newtest , y_test))

Best Wishes;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jean Kossaifi"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 晚上8:16
收件人: "tensorly/tensorly"<tensorly@noreply.github.com&gt;; 
抄送: "自由如风"<1024232797@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [tensorly/tensorly] ValueError: array must not contain infs or NaNs (#178)





 
Thanks @jiyuwangbupt  -- can you post a minimal piece of code to reproduce your issue?
 
Why are you disabling v2_behavior in tensorflow? If your tensors are all in tensorflow you also need to set the backend:
 tl.set_backend('tensorflow')
 
Are your mnist samples in float32 or uint8?
 
Generally, what are you trying to achieve? Currently you  are factorizing 2D images using Tucker, so you may as well do an SVD. Also, since you have a batch of images, you could factorize them jointly using partial_tucker.

**Comment by JeanKossaifi** [comment]
Can you please post a minimal snippet to reproduce your error rather than your whole training looop? 
It would also be useful to see the Traceback (error message). 
What version of tensorly are you using (`tensorly.__version__`)? Can you try upgrading to tensorflow v2? We use that version in TensorLy, it most likely will crash with v1.
