### ISSUE TITLE
Does the orthogonalize parameter in parafac work?

### ISSUE THREAD

**Issue by rutujagurav** [tensorly/tensorly#187]
Hello, 
I noticed that there is an _orthogonalize_ parameter in parafac. 
`parafac(tensor, rank, n_iter_max=100, init='svd', svd='numpy_svd', normalize_factors=False, **orthogonalise=False**, tol=1e-08, random_state=None, verbose=0, return_errors=False, non_negative=False, mask=None, cvg_criterion='abs_rec_error')`

Is it implemented? It isn't defined in the subsequently whereas all other parameters are.

**Comment by JeanKossaifi** [comment]
Thanks for reporting, the doc needs to be updated. 
`orthogonalise` is indeed is implemented and you can use it.

The docstring for it should read
```
orthogonalise : int
    if orthogonalise=K >0 the factors are orthgonalised for the first K iterations
    otherwise the factors are not orthogonalised
```

**Comment by rutujagurav** [comment]
Thanks for the response!
