### ISSUE TITLE
Tensor Train Decomposition 

### ISSUE THREAD

**Issue by Xsurgeon** [tensorly/tensorly#188]
#### Describe the solution you'd like
I would love to know what is the best way to decompose the conv layers, should I use conv3d or should just ignore some the dimension and treat the decomposed layers as 2d instead of 3d

```
 
layer = nn.Conv2d(192, 160, kernel_size=(1, 1), stride=(1, 1))
factors = tl.decomposition.matrix_product_state(layer.weight.data, rank=8)

last = factors[0]  #shape torch.Size([1, 160, 8])
first = factors[1]  #shape torch.Size([8, 192, 1])
second = factors [2] #shape torch.Size([1, 1, 1])
horizontal = factors[3] #shape torch.Size([1, 1, 1])
```
I use able to decompose like that but I am not really sure if this is the right answer similar to tucker decomposition with manipulating the dimension to give me this decomposition, but I don't feel it is the right way to do it. with using rank = 8 
```
Sequential(
  (0): Conv2d(192, 8, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (1): Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), groups=8, bias=False)
  (2): Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), groups=8, bias=False)
  (3): Conv2d(8, 160, kernel_size=(1, 1), stride=(1, 1))
)

```
#### Describe alternatives you've considered
any help with this or just give me hint will be so helpful 

#### Additional context
Thanks

**Comment by JeanKossaifi** [comment]
I'm actually working on a general way to do this -- stay tuned, I'll update when it's ready!

**Comment by Xsurgeon** [comment]
Thanks, any update on this topic.

**Comment by JeanKossaifi** [comment]
I'll ping you when it is ready.

**Comment by JeanKossaifi** [comment]
We now open-sourced [TensorLy-Torch](https://github.com/tensorly/tensorly-torch), which includes implementations of CP and Tucker factorized convolutions and our extension for [Tensor-Train](http://tensorly.org/tensorly-torch/dev/modules/generated/tltorch.factorized_conv.TTConv.html#tltorch.factorized_conv.TTConv).
