### ISSUE TITLE
Error when using KruskalRegressor with X.ndim == 3

### ISSUE THREAD

**Issue by vsaase** [tensorly/tensorly#19]
https://github.com/tensorly/tensorly/blob/f9b9e7885781e21069a7b1a427ee88c961335e2e/tensorly/regression/kruskal_regression.py#L84

When X.ndim==3 then len(W)==2. Now when we skip one dimension in khatri_rao we are left with only one matrix. This leads to an error in kr: ValueError: kr requires a list of at least 2 matrices, but 1 given.

**Comment by JeanKossaifi** [comment]
Thanks for spotting that! 
Should be fixed by bfd67086d1cb6857dd6706b835beebf18f2de4c4.
