### ISSUE TITLE
parafac function doesn't output tuple as detailed in documentation

### ISSUE THREAD

**Issue by nickjtay** [tensorly/tensorly#193]
#### Describe the bug

When applying the code to my own project, I noticed I was not getting the expected output which is described in the documentation as a tuple containing weights and factors. It appears, I am only getting the factors. I checked to see if it was just my code by running the example that is provided in the documentation, and the example code is also erroring out.

```
import matplotlib.pyplot as plt
import tensorly as tl
import numpy as np
from scipy.misc import face
from scipy.ndimage import zoom
from tensorly.decomposition import parafac
from tensorly.decomposition import tucker
from math import ceil


random_state = 12345

image = face()
image = tl.tensor(zoom(face(), (0.3, 0.3, 1)), dtype='float64')

def to_image(tensor):
    """A convenience function to convert from a float dtype back to uint8"""
    im = tl.to_numpy(tensor)
    im -= im.min()
    im /= im.max()
    im *= 255
    return im.astype(np.uint8)

# Rank of the CP decomposition
cp_rank = 25
# Rank of the Tucker decomposition
tucker_rank = [100, 100, 2]

# Perform the CP decomposition
weights, factors = parafac(image, rank=cp_rank, init='random', tol=10e-6)
# Reconstruct the image from the factors
cp_reconstruction = tl.kruskal_to_tensor((weights, factors))

# Tucker decomposition
core, tucker_factors = tucker(image, ranks=tucker_rank, init='random', tol=10e-5, random_state=random_state)
tucker_reconstruction = tl.tucker_to_tensor((core, tucker_factors))

# Plotting the original and reconstruction from the decompositions
fig = plt.figure()
ax = fig.add_subplot(1, 3, 1)
ax.set_axis_off()
ax.imshow(to_image(image))
ax.set_title('original')

ax = fig.add_subplot(1, 3, 2)
ax.set_axis_off()
ax.imshow(to_image(cp_reconstruction))
ax.set_title('CP')

ax = fig.add_subplot(1, 3, 3)
ax.set_axis_off()
ax.imshow(to_image(tucker_reconstruction))
ax.set_title('Tucker')

plt.tight_layout()
plt.show()

``` 

#### Steps or Code to Reproduce

Please run the above code snippet and you will see what I'm referring to.

#### Expected behavior

I am expecting the function ```parafac``` to output a tuple containing weights and factors.

#### Actual result

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-589670da358f> in <module>
     28 
     29 # Perform the CP decomposition
---> 30 weights, factors = parafac(image, rank=cp_rank, init='random', tol=10e-6)
     31 # Reconstruct the image from the factors
     32 cp_reconstruction = tl.kruskal_to_tensor((weights, factors))

ValueError: too many values to unpack (expected 2)
```

#### Versions

Please run the following snippet and paste the output below.

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import tensorly; print("TensorLy", tensorly.__version__)

If you are using another backend than NumPy, please also give us the version for that backend.

Windows-10-10.0.18362-SP0
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
NumPy 1.16.5
SciPy 1.4.1
TensorLy 0.4.3

**Comment by JeanKossaifi** [comment]
You are using an older version of TensorLy, upgrading to the latest version will fix your issue.
