### ISSUE TITLE
How to use the functions in batch-wise way?

### ISSUE THREAD

**Issue by bellos1203** [tensorly/tensorly#199]
First, thank you for the awesome library.

I'm currently trying to implement a pytorch code of rank-1 cp decomposition using the `parafac` function.
However, I'm not sure how can I implement the cp decomposition in a batch-wise way.

For instance, let's assume that we have a tensor T whose shape is (B, H, W), where B is the number of mini-batch samples.
When I directly compute `parafac(T, rank=1)`, the result becomes (Bx1, Hx1, Wx1).
Of course, it is computationally right, and expected output.    

What I want to do is to have B x (Hx1, Wx1) tensors, such as : 
`for i in range(B): 
     weight, factors = parafac(T[i],rank=1)`
Then, the results become B outputs, whose shapes are (Hx1, Wx1).  
This is the result of what I want, but I want to avoid using a loop.

Does the library support such operation? 

Thanks for your consideration in advance!

**Comment by JeanKossaifi** [comment]
We do not support this. There is no dependency between each of the samples in the case you describe so an SVD would need to be applied to each mode of each sample -- I'm not sure whether batching the function would give you any speedup. However, you can easily parallelise the loop.

What output would you expect? A list of CPTensors? Third order tensors concatenating the factors for each sample (e.g. each factor would become of size `(batch_size x dim x rank)`?

**Comment by JeanKossaifi** [comment]
Closing as inactive, feel free to reopen.
