### ISSUE TITLE
error with multiple assignment in 'tucker_to_tensor' function

### ISSUE THREAD

**Issue by RichieHakim** [tensorly/tensorly#201]
#### Describe the bug
Running the 'tucker_decomposition_tensorly_and_pytorch' example notebook fails. Wasn't able to figure out solution from source code myself. The error seems to also occur with 

#### Steps or Code to Reproduce
Using the unmodified jupyter notebook, the same error occurs with pip or dev (github) version of Tensorly. It also occurs whether device is set to 'cpu' or f'cuda:{device_num}'

#### Expected behavior
The notebook should run all the way without error

#### Actual result

```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-644bbfa08589> in <module>
     10 
     11     # Reconstruct the tensor from the decomposed form
---> 12     rec = tucker_to_tensor(core, factors)
     13 
     14     # squared l2 loss

/media/rich/Home_Linux_partition1/github_repos/tensorly/tensorly/tucker_tensor.py in tucker_to_tensor(tucker_tensor, skip_factor, transpose_factors)
     60        full tensor of shape ``(factors[0].shape[0], ..., factors[-1].shape[0])``
     61     """
---> 62     core, factors = tucker_tensor
     63     return multi_mode_dot(core, factors, skip=skip_factor, transpose=transpose_factors)
     64 

ValueError: too many values to unpack (expected 2)

```

#### Versions
Linux-5.4.0-54-generic-x86_64-with-glibc2.10
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
NumPy 1.19.2
SciPy 1.5.2
TensorLy 0.5.0
PyTorch 1.7.0

Using 'pytorch' backend (as per the notebook)

**Comment by RichieHakim** [comment]
error confirmed (verbatim traceback) on separate computer with:
Darwin-19.6.0-x86_64-i386-64bit
Python 3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ]
NumPy 1.19.4
SciPy 1.5.4
TensorLy 0.5.0 (pip)
PyTorch 1.6.0

**Comment by JeanKossaifi** [comment]
Thanks for reporting. The Tucker tensors are now tuple: `rec = tucker_to_tensor(core, factors)` should be `rec = tucker_to_tensor((core, factors))` -- I will update in the main repo.

**Comment by RichieHakim** [comment]
Everything works. Thanks Jean!
