### ISSUE TITLE
Improved non-negative SVD

### ISSUE THREAD

**Issue by aarmey** [tensorly/tensorly#203]
#### Is your feature request related to a problem? Please describe.

Currently it looks like we simply take the standard SVD and then the absolute value of every element, for non-negative CP and Tucker.

#### Describe the solution you'd like

There are [implementations](https://github.com/mims-harvard/nimfa/blob/a37335f249ba74e86b08fef06a63460b02230bb2/nimfa/methods/seeding/nndsvd.py) of non-negative SVD which show [better convergence with non-negative matrix factorization](https://www.sciencedirect.com/science/article/abs/pii/S0031320307004359). I wonder if one of these would be beneficial to implement for non-negative CP and Tucker.

#### Additional context

These methods are also available in sci-kit learn.

**Comment by cohenjer** [comment]
I think that would be great :)

**Comment by JeanKossaifi** [comment]
I agree that would be great! In addition to better SVD init, I also wanted to add better init by averaging columns/rows/fibers of the input.

**Comment by aarmey** [comment]
@cohenjer would you mind if I see that code? Figure it'd help me get it right the first time.

**Comment by cohenjer** [comment]
@aarmey In fact we used the implementation for the nimfa toolbox:
https://github.com/mims-harvard/nimfa/blob/master/nimfa/methods/seeding/nndsvd.py

Not sure we want nimfa as a dependancy however. For an exemple usage,
https://gitlab.inria.fr/amarmore/nonnegative-factorization/-/blob/master/nn_fac/nmf.py

**Comment by aarmey** [comment]
Ok, thanks! This looks similar to scikit-learn's implementation. I don't think we need new dependencies. I have been trying to decide whether this fits more easily into the backend or frontend—it looks like everything will work with the backend operations we have

**Comment by aarmey** [comment]
#204
