### ISSUE TITLE
Error with set_backend()

### ISSUE THREAD

**Issue by ljchang** [tensorly/tensorly#21]
Tensorly appears to be loading with 'mxnet' as a default backend, despite `default_backend = 'numpy'` in `__init__.py`.

I am unable to change the backend using `tl.set_backend('numpy')`.

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-0d71df054526> in <module>()
     14             {k: v for (k, v) in backend.__dict__.items() if not k.startswith('_')
     15             })
---> 16 set_backend('numpy')

<ipython-input-3-0d71df054526> in set_backend(backend_name)
      6 
      7     # reloads tensorly.backend
----> 8     importlib.reload(backend)
      9 
     10     # reload from .backend import * (e.g. tensorly.tensor)

AttributeError: 'module' object has no attribute 'reload'
```

Am I missing something obvious?  Also, there doesn't appear to be specific test for `set_backend()`.

the `'backend'` called by `import.reload` doesn't appear to be specified anywhere in the __init__.py file.

thanks for your help!

**Comment by JeanKossaifi** [comment]
TensorLy is only developed for python 3, in which importlib has no attribute reload.
Updating to Python 3.5 or higher should fix your error.
