### ISSUE TITLE
Greedy pivoting for "orthogonalization" in non-negative methods

### ISSUE THREAD

**Issue by aarmey** [tensorly/tensorly#211]
#### Is your feature request related to a problem? Please describe.

Orthogonalization can help overcome local minimums. This is also a constraint generally applied on the factors in Tucker decomposition. However, Tensorly has generally only taken the absolute value after QR decomposition, which is a poor approximation of the starting matrix.

#### Describe the solution you'd like

Greedy pivoting would be one option, as described [here](http://proceedings.mlr.press/v97/zhang19r/zhang19r.pdf).

#### Describe alternatives you've considered

None.

**Comment by cohenjer** [comment]
@aarmey If you are interested in (nonnegative + orthogonal) Tucker decomposition, in fact these two constraints must yield 1-sparse factors row-wise. There are even dedicated methods for these, for instance [here](https://arxiv.org/pdf/1201.0901.pdf) or [here](https://arxiv.org/pdf/1910.09979.pdf).

But maybe your point was more like ``I want to orthogonalize a few times during the iterations of a NNTucker solver, even though the solution I look for is not orthogonal?''

**Comment by aarmey** [comment]
@cohenjer I was thinking about CP here, even though I used Tucker as an example. (My description could have been clearer.) I think this is better solved by the nnsvd initialization we offer now.
