### ISSUE TITLE
BUG/DOC: Online documentation doesn't build for PARAFAC2 or Tucker

### ISSUE THREAD

**Issue by MarieRoald** [tensorly/tensorly#219]
Currently, there is no online documentation for the `Parafac2` and the `Tucker` class. On my local Linux laptop, I can build the documentation for both these classes. On Windows, however, I am not able to build the documentation for these classes.

I think this may be because of how the documentation files are named. For PARAFAC2, the class API documentation is at `[...]/tensorly.decomposition.Parafac2.html`, and the functional API documentation is at `[...]/tensorly.decomposition.parafac2.html`. If the filesystem doesn't distinguish lower and uppercase letters (like on Windows), we get some problems. The same is the case for Tucker tensors, whereas all other decompositions have different names in the class API and functional API.

I'm not sure what the solution to this problem is. I'm not too familiar with sphinx, but maybe we can use some options to set custom filenames for these cases? If that is not possible, we may have to change the documentation structure, so the class API and functional API for each decomposition are described in the same file. Alternatively, we can alias the classes in a different namespace for the documentation, but I don't think this is the best solution?

**Comment by JeanKossaifi** [comment]
Thanks for opening the issue -- I don't use windows the tests are run on ubuntu so didn't realize this was an issue. Perhaps we could run the tests on windows.

The documentation for [Tucker](http://tensorly.org/dev/modules/generated/tensorly.decomposition.Tucker.html#tensorly.decomposition.Tucker) seems fine on the `/dev` version, will update `/stable`. The doc for Parafac2 also exists on `/dev` but empty -- should be correctly generated once we merge your fix #221 

Generally the documentation of the classes does need improvement, will try to add some more once the API is stable and more tested.

**Comment by MarieRoald** [comment]
Great!  I didn't get any problems with the tests on Windows, but I had trouble building the documentation. I think the problem stems from Windows not distinguishing between a file named `parafac2.html` and `Parafac2.html`. Sphinx will first build the documentation for the object-oriented API in `Parafac2.html`, and then build the documentation for the functional API in `parafac2.html`. Unfortunately, the latter overwrites the former, and we don't get any documentation for the class API. The HTML is built, but the documentation for the Tucker and Parafac2 classes does not work when we build the documentation from Windows. 

To even build it on Windows, I had to copy the `make.bat` file from another project. So that is a hint to new contributors that they shouldn't build the docs from Windows :)

I think it's fine to leave it as is, but we should maybe add a note in the contributor guide stating that if anyone wants to build the documentation on Windows, they should use WSL and start a server there? That way, we are sure that they build the documentation correctly.

Still, I agree that it is probably a good idea to run the tests on Windows if GitHub Actions supports that!

**Comment by JeanKossaifi** [comment]
Fixed in 0fa45c8bfb9babe16262ed9e6649b23748a84e34
