### ISSUE TITLE
Mxnet install dependancy

### ISSUE THREAD

**Issue by jacobgil** [tensorly/tensorly#22]
Hi,
Its not possible to install without mxnet.
However since there are other backends like PyTorch, maybe its best to not have this as a dependency, and choose the backend with a .config file like in Keras.

**Comment by JeanKossaifi** [comment]
Thanks for the feedback!
Indeed both PyTorch MXNet are optional dependencies, I've updated the requirements accordingly.

Currently the backend can be set either by changing the value of `default_backend` in `tensorly.__init__.py` (`'numpy'` by default) or directly in the code by calling `tensorly.set_backend`.

I'll look into having a clear, separate configuration file as you suggest.
