### ISSUE TITLE
Enhancement: Improve naming consistency

### ISSUE THREAD

**Issue by MarieRoald** [tensorly/tensorly#220]
Almost all decomposition implementations are stored in a file with the name `_{{decomposition_name}}`. The exceptions are PARAFAC2 and Robust PCA. Should we rename these modules to `_parafac2.py` and `_robust_decomposition.py`, or is there a reason for these exceptions?

**Comment by JeanKossaifi** [comment]
The underscore was to prevent any collision/confusion between the name of the module and the name of a function it implements (e.g. `tensorly.tucker` for the module and `tensorly.tucker.tucker` for the function). 

I think parafac2 should indeed be renamed but for robust_decomposition it doesn't need to be changed as there is no such confusion.

**Comment by MarieRoald** [comment]
Sounds reasonable :) I renamed the `_robust_decomposition` back to `robust_decomposition` in #221
