### ISSUE TITLE
A clearer interface to SVD options

### ISSUE THREAD

**Issue by aarmey** [tensorly/tensorly#227]
I think we may want to use the opportunity to add some documentation, perhaps in the user_guide, either in the [backend](https://github.com/tensorly/tensorly/blob/main/doc/user_guide/backend.rst) section or in a new page? We can there explain the difference between the three provided interfaces. 

I'd really rather avoid converting to NumPy as much as possible as it breaks the computational graph in some backends and causes surprising issues (e.g. if running the method on GPU).

On the API side, I'm wondering whether we want to provide a function `partial_svd` (or even just `svd`) and an additional `implementation` (or `method`?) :

```python
def partial_svd(matrix, n_eigenvecs, implementation='truncate')
```
where 
```
implementation : {'truncate', 'numpy', 'eish'}

          - truncate : uses the backend's native SVD function and truncates it
          - numpy : uses the efficient Sparse SVD from Scipy to only compute the required eigenvalues
          - symeig : uses the native backend's symeig to leverage the symmetry in the covariance matrix when computing the SVD
```

_Originally posted by @JeanKossaifi in https://github.com/tensorly/tensorly/issues/217#issuecomment-783381531_

**Comment by JeanKossaifi** [comment]
Added in #429.
