### ISSUE TITLE
Parafac: set fixed_modes default to None

### ISSUE THREAD

**Issue by JeanKossaifi** [tensorly/tensorly#228]
In parafac, currently `fixed_modes` defaults to an empty list, which is mutable and mutations of that list would be preserved from one call to another. Set the default to None and initialize accordingly in the core of the function. 

https://github.com/tensorly/tensorly/blob/ab504452039c3fe4f46351a622dd177b29778bd2/tensorly/decomposition/_cp.py#L176

**Comment by cohenjer** [comment]
It's my bad :/ I can fix it easily when I find some time

**Comment by JeanKossaifi** [comment]
Not at all, it's no-one's bad - the likelihood of the default value being mutated is fairly small so that's just extra precaution (from experience mutated default parameters can cause hard to debug issues!). I just opened the issue so we'd remember and figured it could be good first time PR for new contributors :)

**Comment by yngvem** [comment]
@JeanKossaifi This should probably be closed? Current function signature of `parafac` is

```python
def parafac(tensor, rank, n_iter_max=100, init='svd', svd='numpy_svd',
            normalize_factors=False, orthogonalise=False,
            tol=1e-8, random_state=None,
            verbose=0, return_errors=False,
            sparsity=None,
            l2_reg=0,  mask=None,
            cvg_criterion='abs_rec_error',
            fixed_modes=None,
            svd_mask_repeats=5,
            linesearch=False):
```

**Comment by JeanKossaifi** [comment]
Yes, absolutely, thanks @yngvem !
