### ISSUE TITLE
`robust_pca` does not compute on GPU using `mxnet` backend

### ISSUE THREAD

**Issue by wdeback** [tensorly/tensorly#23]
(Disclaimer: This question might be more appropriate for a user forum -- but couldn't find one.)

Hi,

I'm trying to do video background subtraction as in [this example](https://jeankossaifi.github.io/tensorly/rpca.html#Example-on-a-video)  using the `mxnet` backend on GPU. 

I have successfully ran [tensorly/mxnet notebooks](https://github.com/JeanKossaifi/tensorly-notebooks/tree/master/04_mxnet_backend) with GPU acceleration by using `context`s, e.g.:

```
context = mx.gpu()
shape = [150, 100, 100] # <== larger tensors should be faster on GPU
tensor = tl.tensor(rng.random_sample(shape), ctx=context)
```

That is, tensorly with mxnet backend nicely switched from CPU to GPU transparently.  

However, this approach does not seem to work for `robust_pca`.

What I tried was to I wrap my video data `data` in a tensor `X` in a GPU context:

```
X = tl.tensor(data, ctx=mx.gpu()) # <- GPU context 
X = X.astype(np.float32)
tl.context(X)
```

and used this as an input for `robust_pca`:

```
from tensorly.decomposition import robust_pca
D, E = robust_pca(X, reg_E=0.05, learning_rate=1.6, n_iter_max=20)
```

Although the resulting tensors `D` and `E` are also in `gpu` context (as well as the tensors used internally, I checked), the computation itself seems to be done on CPU (as judged by CPU/GPU activity stats). Not, as expected, on GPU.

Am I missing something here? How do I switch this computation to GPU?

Here's the full notebook: https://gitlab.com/wdeback/robustPCA/blob/master/RobustPCA_on_GPU%3F.ipynb

Thanks in advance!

**Comment by JeanKossaifi** [comment]
Hi @wdeback 

Thanks for the detailed feedback!

Proper support for the context of input tensors has been added in master (033ed618d47bae3af0e40b86c7d326615e5aceca). 

I am planning to release a new version soon on PyPi but in the meantime the easiest way is to install TensorLy from master:

```
git clone https://github.com/tensorly/tensorly
cd tensorly
pip install -e .
```

Or directly:

```
pip install git+https://github.com/tensorly/tensorly
```

I incremented the version in the latest commit so you can check whether you are using the correct version by checking that ```tensorly.__version__``` returns `0.3.0`.

Let me know if you have any more questions or if this doesn't solve your issue!

**Comment by wdeback** [comment]
Thanks for your prompt reply, @JeanKossaifi.

> Proper support for the context of input tensors has been added in master (033ed61).

I am already using the master (build from source) including the commit with propagation of contexts such as:

```
D = T.zeros_like(X, **T.context(X))
```

and I confirmed that the internal tensors (`D`,`E`, `L_x`, etc.) indeed live in the gpu context (See `Out [9]` in [this notebook](https://gitlab.com/wdeback/robustPCA/blob/master/RobustPCA_on_GPU%3F.ipynb).

Nevertheless, most computation of the `robust_pca()` function itself is to be done on cpu. I assume is not the intended behavior.

Any idea how I test this any further to help you identifying the issue?

**Comment by JeanKossaifi** [comment]
As of now MXNet doesn't yet have an implementation of the SVD, so for every call to the singular-value thresholding operator, the input tensor if copied to CPU, where SVD is performed by NumPy and the result copied back to GPU: my guess is most the time is wasted there..

I am experimenting with the `syevd` but it does not seem to be robust enough for most use cases..

**Comment by wdeback** [comment]
> MXNet doesn't yet have an implementation of the SVD, so for every call to the singular-value thresholding operator, the input tensor if copied to CPU, where SVD is performed by NumPy and the result copied back to GPU

Aha, yes, that makes sense.  Thanks for the heads up.

I'll keep an eye on future developments. (Very nice project, BTW.)
