### ISSUE TITLE
Bug when n_eigenvecs is None in truncated_svd

### ISSUE THREAD

**Issue by caglayantuna** [tensorly/tensorly#233]
#### Describe the bug
Hello, I have an issue with truncated_svd function. After the last commit, `partial_svd` function in `backend/core.py` calls `truncated_svd` function in line 836 `if (n_eigenvecs is None)`. However, there is a type error in line 901 because '<' is not supported between instances of 'int ' and NoneType. 

#### Steps or Code to Reproduce
Maybe, we can take into account None for n_eigenvecs in line 901 as;

```python
if (n_eigenvecs is not None) and (max_dim < n_eigenvecs):
```

**Comment by JeanKossaifi** [comment]
Good point, we should test for that case and return all eigenvecs and probably also add a small unit-test for that bug.
