### ISSUE TITLE
Issue with PARAFAC inputting an cuda.FloatTensor

### ISSUE THREAD

**Issue by lokeshveeramacheneni** [tensorly/tensorly#242]
I tried to run PARAFAC decomposition with a cuda.FloatTensor as below 
`tensor_ = tl.tensor(org_tensor, device='cuda')
    tensor_ = tensor_.to('cuda')` 
[org_tensor is a tensor on CPU]
as suggested in http://tensorly.org/dev/user_guide/backend.html#on-gpu. 
The context of tensor_ variable is 
{'dtype': torch.float32, 'device': device(type='cuda', index=0), 'requires_grad': False}

When inputting this tensor to PARAFAC, at line 319 `pseudo_inverse = pseudo_inverse*tl.dot(tl.conj(tl.transpose(factor)), factor)` either pseudo_inverse or factor is on cpu and other is on GPU. 
Are my initializations wrong or PARAFAC doesn't support GPU operations?

**Comment by JeanKossaifi** [comment]
Hi @lokeshveeramacheneni, 

We support GPU everywhere in TensorLy. Can you post your version of PyTorch and TensorLy and some minimal code to reproduce your issue?

It works fine on my end:
```python
import tensorly as tl
tl.set_backend('pytorch')
from tensorly import random
from tensorly.decomposition import parafac

tensor = random.random_tensor((10, 10, 4), device='cuda:0')
print(f'Tensor is on device={tensor.device}.')

cp = parafac(tensor, rank=5)
print(cp.weights.device, [f.device for f in cp.factors]) 
```

Output: 
```
Tensor is on device=cuda:0.
cuda:0 [device(type='cuda', index=0), device(type='cuda', index=0), device(type='cuda', index=0)]
```

**Comment by lokeshveeramacheneni** [comment]
Hello @JeanKossaifi 

default 'svd' initializations work for me also. I am working with the random initialization, it throws error. i.e.,
```
import tensorly as tl
tl.set_backend('pytorch')
from tensorly import random
from tensorly.decomposition import parafac

tensor_ = random.random_tensor(shape=(10, 10, 4), device='cuda:0', dtype=tl.float32)
print(tl.context(tensor_), flush=True)
decomposition = parafac(tensor_, rank=5, init='random')
```

Pytorch version - 1.7.0
Tensorly version - 0.5.0

**Comment by JeanKossaifi** [comment]
Random init also works for me - can you try updating your TensorLy version?

**Comment by lokeshveeramacheneni** [comment]
0.5.1 version works for me.
Many thanks for your immediate response
