### ISSUE TITLE
Bug in CP symmetric power iteration?

### ISSUE THREAD

**Issue by chrisyeh96** [tensorly/tensorly#245]
https://github.com/tensorly/tensorly/blob/da0eae91c5e2c0c68f98c1ec7a415ac58141ede9/tensorly/decomposition/_symmetric_cp.py#L70

It seems like that the code assumes that the tensor is only 3rd order. Should it be the following instead?

```python
 deflated = tensor - outer([best_factor]*order)*eigenval
```

**Comment by JeanKossaifi** [comment]
Yes, indeed, thanks @chrisyeh96! I see you've already opened a PR, could you also make that change there?

**Comment by chrisyeh96** [comment]
Done! Also fixed another bug while I was at it. Can you review and merge #244?

Also, what's the process for new releases? Curious when these changes will actually ship.

**Comment by JeanKossaifi** [comment]
Fixed in #244 - thanks @chrisyeh96.

I'm planning to make a release by the end of the month, but I could make one sooner if you need to use the pypi version rather than install from source?

**Comment by chrisyeh96** [comment]
I don't have any urgent need for a new release. I'm just curious how you decide when to make new releases.

**Comment by JeanKossaifi** [comment]
Typically, when either there is demand/need for it; there are sufficient new features to warrant a release, or we fixed important issues.
