### ISSUE TITLE
Complex Support

### ISSUE THREAD

**Issue by taylorpatti** [tensorly/tensorly#246]
Here are 3 issues with complex support:

```python
import math
import tensorly as tl
from tensorly import testing
from tensorly.decomposition import parafac, tensor_train
```

1.) Issue with "norm" from backend

```python
def test_norm_complex():
    """The norm at a minimum does not work for complex tensors with order = 2, as
    it should be tensor*conj(tensor), not tensor**2. I'm not sure about the other
    orders, they too should be checked."""
    tensor = tl.tensor([1, 1j, 0], dtype=torch.complex64)
    norm = tl.norm(tensor)
    testing.assert_array_almost_equal(norm, math.sqrt(2), decimal=6)
```

2.) Issue with CP tensor decomposition/recomposition with parafac and cp_to_tensor - fails in general by giving very wrong answer

```python
def test_cp_complex():
    """Test that parafac decomposition and cp_to_tensor work for complex tensors.
    Produces incorrect answers. Code needs debugging for complex tensors."""
    shape = (2, 4, 3, 2)
    tensor = tl.randn(shape) + tl.randn(shape)*1j
    decomp = parafac(tensor, rank=100)
    recomp = tl.cp_to_tensor(decomp)
    testing.assert_array_almost_equal(tensor, recomp)
```

3.) Issue with TT tensor decomposition/recomposition with tensor_train and tt_to_tensor - fails for TensorFlow and MxNet, but as it still works for 3 backend

```python
def test_tt_complex():
    """Test that tensor_train decomposition and tt_to_tensor work for complex tensors.
    Works for some backends, but not for TensorFlow and MxNet."""
    shape = (2, 4, 3, 2)
    tensor = tl.randn(shape) + tl.randn(shape)*1j
    decomp = tensor_train(tensor, rank=(1, 8, 24, 8, 1))
    recomp = tl.tt_to_tensor(decomp)
    testing.assert_array_almost_equal(tensor, recomp)
```

**Comment by JeanKossaifi** [comment]
It would be great to support complex tensors for CP. I fixed the norm and `cp_to_tensor` and MXNet doesn't support complex dtypes but CP still needs work.

Does anyone have experience with complex tensors? @aarmey @cohenjer @caglayantuna @merajhashemi

**Comment by aarmey** [comment]
I don't have experience with them but this does seem like something that would be great to support. Probably best to start with testing? Since essentially everything should work, perhaps we can add these separate test cases, and then also add complex cases to existing tests with [`pytest.mark.parameterize`](https://docs.pytest.org/en/stable/parametrize.html)?
