### ISSUE TITLE
The difference between parafac and parafac_power_iteration

### ISSUE THREAD

**Issue by Only-bottle** [tensorly/tensorly#248]
I am going to use CP decomposition as a Tensorly library.
I found that there are parafac and parafac_power_itation in the document and github.
Parafac can be checked because reference material exists, but parafac_power_iteration has not found a reference material.
Could you explain parafac_power_iteration?

**Comment by JeanKossaifi** [comment]
Hi, glad to hear you're planning to use TensorLy. 
parafac_power_iteration computes the CP decomposition via robust tensor power iteration, there are several references on the subject, you can check [Tensor Decompositions for Learning Latent Variable Models](https://jmlr.org/papers/volume15/anandkumar14b/anandkumar14b.pdf), JMLR 2015 and the monograph [Spectral Learning on Matrices and Tensors](https://arxiv.org/abs/2004.07984).

Let us know if you have other questions.

**Comment by Only-bottle** [comment]
Thank you for your reply.

When checking the parafac and parafac_power_iteration functions in github,
parafac uses SVD to make 4D matrix into 4D matrix and understand it as a
way to obtain optimal factors with ALS algorithm. parafac_power_iteration
understands how to obtain best factors by setting the initial matrix while
repeating n_repet and repeating it as much as n_iteration.

So, I think that doing the same CP decomposition in different ways.
I wonder if what I understand is right.

Also, I wonder if there is a problem with trying to use power_iteration
instead of parafac to use CP decomposition.

Thanks

Byeongman.

2021년 3월 23일 (화) 오전 8:54, Jean Kossaifi ***@***.***>님이 작성:

**Comment by JeanKossaifi** [comment]
Yes, they are different algorithms to decompose a tensor into a CP form. The main [CP](http://tensorly.org/stable/modules/generated/tensorly.decomposition.CP.html#tensorly.decomposition.CP) class uses alternating least squares while [CPPower](http://tensorly.org/stable/modules/generated/tensorly.decomposition.CPPower.html#tensorly.decomposition.CPPower) uses robust tensor power iterations. 

Why do you think there is a problem with power iterations?

**Comment by Only-bottle** [comment]
I don't think there's a problem with power operation.
I was just curious about the difference between CP and CPPower.

Can you tell me which one you think is recommended to use, CPPower or CPPower?

And which factor do you think is more important in CPPower, n_repetition or n_iteration?
Asking this question is concerned about whether to give a greater value, n_repetition or n_iteration.

Thank you for your reply.

**Comment by Only-bottle** [comment]
In addition, there is OOM in init='svd", svd='partial_svd", input Tensor= [512, 512, 3, 3] in CP.
I checked the cause and found that if the value of n_eigenvecs (rank=256) is greater than min_dim, full_matrics returns true.
For this reason, it is understood that OOM occurs while generating (786432, 786432) when SVD (3, 786432).
Can you tell me the solution to this?

**Comment by JeanKossaifi** [comment]
The choice of algorithms really depends on your problem and what you want to achieve and in general you'd have to validate the hyper-parameters. For instance, you may want to use a very small value for l2_reg to regularize the problem. 

Typically CP via ALS performs well on most problems so I would start there unless you have specific needs for the power iterations. 

Regarding the memory issue, you can either reduce the rank or use a random initialization to avoid having to compute the svd (`init='random'`).

**Comment by Only-bottle** [comment]
Okay. Thank you.
I have a few concerns right now, so if you have any advice, please.

I want to do CP decomposition. You want to use parafac (init='svd') in that way. However, OOM occurs when the input_tensor mentioned earlier is [512, 512, 3, 3].

As a solution to this, I thought as follows.

1. init='random' as your advice. However, this seems to improve performance only when the value of n_iter_max is large. It also takes a long time depending on n_iter_max. :(
2. Modify the code so that the value of full_matrices is always used as false in the partial_svd. I'd like to hear your opinion about this method.
3. Use power_iteration. Comparing the performance with the same conditions as parafac, there was no significant difference. The problem of OOM in SVD has also been solved. So now I think it would be better to use power_iteration instead of parafac.

I am sorry that I wrote a lot about my thoughts.
I'd like some advice from you about the above.
Thank you for always answering kindly.

**Comment by Only-bottle** [comment]
Can I give you some advice on my questions?

Thanks.

**Comment by JeanKossaifi** [comment]
As I said, the choice of algorithm really depends on your problem, if power iteration works well for your problem then you can use that. You may want to try other decompositions, such as Tucker.

There is a tradeoff between speed and memory usage. Setting init to 'random' is not to improve performance but avoid the memory cost of SVD. In general random initialization still works reasonably well. Always setting full_matrices to False will result in incorrect sizes, feel free to try it for yourself!

Questions like this might be better suited for [discussion](https://github.com/tensorly/tensorly/discussions), e.g. Q&A rather than in issues, let's continue there if you have more questions.
