### ISSUE TITLE
Tensorly cannot be installed if the dependencies are not met beforehand.

### ISSUE THREAD

**Issue by jesuscast** [tensorly/tensorly#25]
## Problem
Tensorly cannot be installed if the dependencies are not met beforehand.
The `setup.py` script is importing tensorly to grab the version; this is problematic, since importing tensorly requires that all the dependencies are already met, and we are importing it before `setup(**config)` gets run.

This defeats the purpose of using `'install_requires': ['numpy', 'scipy']`

**Comment by JeanKossaifi** [comment]
Agreed, thanks for raising the issue and writing a fix!

**Comment by JeanKossaifi** [comment]
Closed by 9f87b657392d28ac15fa5ed7421269bc5af66856.
