### ISSUE TITLE
Does tensorly work with Tensorflow 2.3+?

### ISSUE THREAD

**Issue by astrogilda** [tensorly/tensorly#259]
Hi! I came across tensorfly via your recent presentation at NVIDIA GTC. I am curious about applying tensorly to compress my tensorflow model. Does tensorly work with the latest versions of tensorflow?

**Comment by JeanKossaifi** [comment]
Hi @astrogilda, glad to hear! Yes, you can use TensorLy with any of the backends transparently whether that's NumPy, PyTorch, TensorFlow, MXNet, CuPy or JAX. 

For TensorFlow, just set the backend as follows:
```python
import tensorly as tl
tl.set_backend('tensorflow')
```

Let us know if you have any issue.

**Comment by astrogilda** [comment]
Thanks Jean!
Follow up question - say my model consists of 10 layers, out of which 3 are
custom layers for which you don't have compression available in tensorly
yet. Can I simply compress the 7, and concatenate them with the original 3?
In other words, can I mix-and-match?

Best,
Sankalp Gilda

**Comment by JeanKossaifi** [comment]
TensorLy itself does not provide neural networks layers. For that, we have [TensorLy-Torch](https://github.com/tensorly/torch), which is PyTorch only and provides out-of-the-box tensor-based deep net layers. But the decomposition of the weights is independent from the layers, so you can simply pass on your layer's weight to any decomposition available in TensorLy (e.g. Parafac, Tucker, Tensor-Train etc) and get back a factorized version.
