### ISSUE TITLE
Dangerous dependency handling during testing.

### ISSUE THREAD

**Issue by jesuscast** [tensorly/tensorly#27]
There is no guarantee that the dependencies used during testing will match the dependencies the project actually needs.

Currently we test using a conda environment that gets set up in the following manner:
` - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy`

But there is no guarantee that the version used by conda will match the version in requirements.txt

**Comment by JeanKossaifi** [comment]
Thanks for reporting. As mentioned in the other issue, ideally i'd rather there be no version specified in requirements.txt, to make it easier to users who may have another compatible version of NumPy/Scipy installed (will check what is happening with the latest NumPy!)
