### ISSUE TITLE
how to handle complex numbers?

### ISSUE THREAD

**Issue by ziofil** [tensorly/tensorly#3]
I'm trying to use `parafac` on a complex tensor. I can handle the real and imaginary parts separately by calling `PR = parafac(np.real(T), rank = k)` and `PI = parafac(np.imag(T), rank = k)` and then I can operate on the two parts separately. However, what I really need is the decomposition of T into complex rank-1 tensors. Is there a simple way of achieving this?

**Comment by JeanKossaifi** [comment]
You could apply parafac to the concatenation of the real and imaginary part.
