### ISSUE TITLE
RuntimeWarning: invalid value encountered in sqrt   S = np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, np.sqrt(S))

### ISSUE THREAD

**Issue by nehSgnaiL** [tensorly/tensorly#341]
Hi, there. Could anyone give me a help?

#### Describe the bug
RuntimeWarning: invalid value encountered in sqrt
  S = np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, np.sqrt(S))
 
ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV.

#### Steps or Code to Reproduce

For instance:

```python
import tensorly as tl
from tensorly.decomposition import tucker, non_negative_tucker
import numpy as np

if __name__ == '__main__':
    x_list = [[[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]], [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]], [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]], [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]], [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]], [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]], [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]], [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0]], [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]]
    x_array = np.array(x_list).reshape((9, 24, 2))
    x_tensor = tl.tensor(x_array, dtype=tl.float32)
    # tucker decomposition
    core, factors = non_negative_tucker(x_tensor, rank=[2, 2, 2])
```

#### Expected behavior
return the result of tucker decomposition

#### Actual result
 
D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\backend\core.py:916: RuntimeWarning: invalid value encountered in sqrt
  S = np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, np.sqrt(S))
Traceback (most recent call last):
  File "XX/issue.py", line 10, in <module>
    core, factors = non_negative_tucker(x_tensor, rank=[2, 2, 2])
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition\_tucker.py", line 252, in non_negative_tucker
    core, factors = tucker(tensor, rank)
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition\_tucker.py", line 206, in tucker
    svd=svd, tol=tol, random_state=random_state, mask=mask, verbose=verbose)
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition\_tucker.py", line 109, in partial_tucker
    eigenvecs, _, _ = svd_fun(unfold(core_approximation, mode), n_eigenvecs=rank[index], random_state=random_state)
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\backend\core.py", line 914, in partial_svd
    np.dot(matrix.T.conj(), matrix), k=n_eigenvecs, which='LM', v0=v0
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 1687, in eigsh
    params.iterate()
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 573, in iterate
    raise ArpackError(self.info, infodict=self.iterate_infodict)
scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV. 

Process finished with exit code 1

#### Versions

Windows-10-10.0.19041-SP0
Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
NumPy 1.19.2
SciPy 1.5.2
TensorLy 0.6.0

**Comment by caglayantuna** [comment]
Hello, I ran your code without any error. Could you update your tensorly and try again? I found an [update](https://github.com/tensorly/tensorly/commit/45e64d9716871073415dab5f647c89d7839a88fe#diff-3e1da4d92e2d739adfbcf25b91c53643851f4da8d7948b314f4e74ff8d93a748) where your code fails.

**Comment by nehSgnaiL** [comment]
@caglayantuna Thanks a lot. The version of Tensorly in anaconda was 0.6.0, and I used the command "pip install -U tensorly" to update my tensorly to 0.7.0.
While I try it again, a new error about  "module 'tensorly' has no attribute 'SVD_FUNS'" seems to appear.

#### Actual result
Traceback (most recent call last):
  File "XX/issue.py", line 26, in <module>
    core, factors = non_negative_tucker(x_tensor, rank=[2, 2, 2])
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition\_tucker.py", line 319, in non_negative_tucker
    core, factors = tucker(tensor, rank)
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition\_tucker.py", line 271, in tucker
    verbose=verbose)
  File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition\_tucker.py", line 137, in partial_tucker
    svd_fun = tl.SVD_FUNS[svd]
AttributeError: module 'tensorly' has no attribute 'SVD_FUNS'

#### Versions
Windows-10-10.0.19041-SP0
Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
NumPy 1.19.2
SciPy 1.5.2
TensorLy 0.7.0

**Comment by nehSgnaiL** [comment]
> @caglayantuna Thanks a lot. The version of Tensorly in anaconda was 0.6.0, and I used the command "pip install -U tensorly" to update my tensorly to 0.7.0. While I try it again, a new error about "module 'tensorly' has no attribute 'SVD_FUNS'" seems to appear.
> 
> #### Actual result
> Traceback (most recent call last): File "XX/issue.py", line 26, in core, factors = non_negative_tucker(x_tensor, rank=[2, 2, 2]) File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition_tucker.py", line 319, in non_negative_tucker core, factors = tucker(tensor, rank) File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition_tucker.py", line 271, in tucker verbose=verbose) File "D:\Software\Anaconda3\envs\pytorch\lib\site-packages\tensorly\decomposition_tucker.py", line 137, in partial_tucker svd_fun = tl.SVD_FUNS[svd] AttributeError: module 'tensorly' has no attribute 'SVD_FUNS'
> 
> #### Versions
> Windows-10-10.0.19041-SP0 Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)] NumPy 1.19.2 SciPy 1.5.2 TensorLy 0.7.0

omg, I created new environment to install tensorly 0.7.0 via pip, and that's perfectly run without any error.
