### ISSUE TITLE
Hard to handle TypeError: transpose() ~

### ISSUE THREAD

**Issue by Jiyny** [tensorly/tensorly#346]
Hi, I have a problem with my code and can't understand or solve the error :(
Any advice would be such a great help!

I want to use non_negative_parafac (actually parafac is fine to!) to my tensor but an error keeps coming out.

The tensor I made has torch.Size([98, 94, 94]) and it's a torch.DoubleTensor. (the name of the tensor I made is 'AMT_3d')

However, when I execute below code:
factors = parafac(AMT_3d,rank=2)

The below error pops out :((((
/lib/python3.8/site-packages/numpy/core/numeric.py in moveaxis(a, source, destination)
   1463         order.insert(dest, src)
   1464 
-> 1465     result = transpose(order)
   1466     return result
   1467 

**TypeError: transpose() received an invalid combination of arguments - got (list), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)**

I am so stuck with it. Thank you for spending your time.

**Comment by abhinavgoel95** [comment]
How did you solve this problem?
