### ISSUE TITLE
Unable to use pytorch as the backend

### ISSUE THREAD

**Issue by rtmatx** [tensorly/tensorly#35]
I tried to use pytorch as the backend by using `tl.set_backend('pytorch')`

But I get an error mentioning that `ModuleNotFoundError: No module named 'tensorly.backend.pytorch_backend'`

I have pytorch installed and can check using `import torch`. I run pytorch code on my GPU without any issues

Thanks

**Comment by JeanKossaifi** [comment]
Hi @rtmatx!
Which version of TensorLy are you using did you install it with pip?
It might be that you are using an older version that doesn't have the pytorch backend yet ..

To check the version:
```python
import tensorly as tl
tl.__version__
```

**Comment by rtmatx** [comment]
Thanks @JeanKossaifi 

I checked the version and it solved the issues. I first installed using pip last night and it installed previous version but today I updated with installation from source
