### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by EgorSevriugov** [tensorly/tensorly#351]
#### Describe the bug
Simple run example of code proposed on official site and got an error: "AttributeError: module 'tensorly' has no attribute 'SVD_FUNS'"

#### Steps or Code to Reproduce

I have run your code example "Image compression via tensor decomposition"

#### Expected behavior
For proposed example there should be compressed versions of particular image

#### Actual result

The result is an error: "module 'tensorly' has no attribute 'SVD_FUNS'"

#### Versions
Linux-5.4.0-65-generic-x86_64-with-debian-buster-sid
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
NumPy 1.19.5
SciPy 1.2.1
TensorLy 0.7.0

**Comment by JeanKossaifi** [comment]
Hi @EgorSevriugov,

I cannot reproduce your error on my machine, the code runs fine. The examples are generated at each PR as well so it also runs in our test environment.

Can you post your error message? Do you run exactly [this code](http://tensorly.org/dev/auto_examples/decomposition/plot_image_compression.html#sphx-glr-auto-examples-decomposition-plot-image-compression-py)?

Can you try to run the code from a different folder - it might be a local import issue.

**Comment by FlyGreyWolf** [comment]
> Hi @EgorSevriugov,
> 
> I cannot reproduce your error on my machine, the code runs fine. The examples are generated at each PR as well so it also runs in our test environment.
> 
> Can you post your error message? Do you run exactly [this code](http://tensorly.org/dev/auto_examples/decomposition/plot_image_compression.html#sphx-glr-auto-examples-decomposition-plot-image-compression-py)?
> 
> Can you try to run the code from a different folder - it might be a local import issue.

yes, I have this problem too. The code is download from repository and not modified. The code is 
`weights, factors = parafac(X, rank=2)`  in the file 'cp_decomposition.ipynb'.

**Comment by FlyGreyWolf** [comment]
> #### Describe the bug
> Simple run example of code proposed on official site and got an error: "AttributeError: module 'tensorly' has no attribute 'SVD_FUNS'"
> 
> #### Steps or Code to Reproduce
> I have run your code example "Image compression via tensor decomposition"
> 
> #### Expected behavior
> For proposed example there should be compressed versions of particular image
> 
> #### Actual result
> The result is an error: "module 'tensorly' has no attribute 'SVD_FUNS'"
> 
> #### Versions
> Linux-5.4.0-65-generic-x86_64-with-debian-buster-sid Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0] NumPy 1.19.5 SciPy 1.2.1 TensorLy 0.7.0

You should try to use 
`conda install -c tensorly tensorly`

**Comment by aarmey** [comment]
This issue is specific to Python v3.6. v3.6 is no longer supported, so I would recommend upgrading.
