### ISSUE TITLE
Similarity metric between CP tensors invariant to scale, sign, permutation

### ISSUE THREAD

**Issue by aarmey** [tensorly/tensorly#352]
It'd be nice to have a built-in way to compare CP tensors that doesn't have sign, scale, and permutation issues. Perhaps I could implement the [CorrIndex](https://hal.archives-ouvertes.fr/hal-03230210/document)? Our lab has dealt with this problem when comparing PARAFAC runs, and I recently met another systems biologist TensorLy user having the same problem.

**Comment by cohenjer** [comment]
I think this is related to #316 , because if we can align two CP then comparison nay be done on the factors (which will be permuted and scaled so more readily comparable).
I guess CorrIndex (which I was unfamiliar with) is another solution but a little less intuitive ? Definitively valuable to have it anyways but I guess this will not solve #316.

**Comment by aarmey** [comment]
Agreed. It wasn't obvious to me that it would be possible to add

**Comment by aarmey** [comment]
@cohenjer, agreed. It wasn't obvious to me that it would be possible to do #316 without SciPy though? Is there information on how often a greedy approach would find a suboptimal solution?

On a more basic level, perhaps we could use a simple operation to permute the factors first. I know I've implemented this multiple times now, and it becomes annoying when you have multiple backends.

**Comment by JeanKossaifi** [comment]
Would be great to have CorrIndex! For #316 I would thinking just a simple utility fun, e.g. correlation based. 

It might be a good time to discuss dropping the most cumbersome backends for the next big version and converging to the array API for all backends. We could use the opportunity to clean up / unify the code base and API.

**Comment by cohenjer** [comment]
@JeanKossaifi I would be VERY happy to discuss dropping annoying backends.

@aarmey This could be a method of the CP tensor class, pretty easy to implement and also valuable imo.

Regarding the suboptimality of a correlation/greedy based method, I think that:
- When the two CP tensors compared are similar and well conditionned (no colinearity in factors or such), correlation is good enough.
- When the two CP tensors are very different or degenerate, the greedy approach may be very different from the optimal, linear programming approach (which requires e.g. the Hungarian algorithm indeed implemented in SciPy).
 
Nevertheless, it is not very sensible to try and find the best permutation to compare tensors when they are extremely different; we might artificially reduce distance between CP tensors. So correlation/greedy method might be good enough (although I typically use the optimal permutation in my research works).

**Comment by cohenjer** [comment]
Back on this topic, could we use scipy as a dependency here? It is already a dependency of tensorly right? With scipy we could make a PR to close this issue pretty easily.

**Comment by aarmey** [comment]
We now have a greedy matching approach and the corrindex. Closing!
