### ISSUE TITLE
Simplex Projection does not work

### ISSUE THREAD

**Issue by cohenjer** [tensorly/tensorly#354]
#### Describe the bug
I ran the `simplex_prox` new function located in proximal.py from the AOADMM PR, and it turns out it does not work.

Moreover the function can be improved, for instance by allowing 1-d tensor input and removing some computation overhead.

#### Steps or Code to Reproduce

For instance:

```python
from tensorly.tenalg.proximal import simplex_prox

t = tl.tensor([[0.4,1.5,1],[0.5,2,3],[0.6,0.3,2.9]])
print(simplex_prox(t,parameter=1))
```
produces
```python
[[0.35 0.5  0.  ]
 [0.45 1.   1.  ]
 [0.55 0.   0.9 ]]
```
 which columns do not sum to 1.

Instead the correct output should be
```python
[[0.23333333 0.25       0.        ]
 [0.33333333 0.75       0.55      ]
 [0.43333333 0.         0.45      ]]
```
By the way, the current unit test passes by chance; I suggest we replace it with another one such as above.

#### Bug source

The bug mainly comes from the fact that one of the inner computations is missing a division. I have cooked a corrected version of the function, which I will run by @caglayantuna to fine tune. We will make the correction PR asap.

**Comment by JeanKossaifi** [comment]
Fixed in #363
