### ISSUE TITLE
Handling big datasets for Robust PCA

### ISSUE THREAD

**Issue by rtmatx** [tensorly/tensorly#36]
I tried to run Robust PCA on a torch array. The dimensions are around 500000*375. They array can perfectly fit on my GPU as I ran robust matrix decomposition without any issues. I am sure why robust PCA can't fit or even require 2310 GB of memory. Also is the memory GPU or CPU memory ?

My system has 512 GB of CPU memory and 32 GB of GPU memory

`$ Torch: not enough memory: you tried to allocate 2310GB. Buy new RAM! at /pytorch/torch/lib/TH/THGeneral.c:246`

**Comment by JeanKossaifi** [comment]
Could you give more information about your error?
The issue might be with the PyTorch `svd`, it seems there are issue when running it on large tensors..

**Comment by rtmatx** [comment]
I will run pytorch svd on the same dataset and report any issues.

**Comment by rtmatx** [comment]
I ran the dataset with PyTorch SVD and it reproduces the same error as mentioned above. Since it is a PyTorch issue, I am closing this now. 

Thanks

**Comment by JeanKossaifi** [comment]
Following up on this, in the mean time you could either convert your array to NumPy and use the Numpy backend to perform the Robust tensor PCA or we could temporarily add a function that performs the SVD only in NumPy and the rest of the computation in PyTorch.

**Comment by rtmatx** [comment]
I ch

**Comment by rtmatx** [comment]
I used the default backend of `tensorly` but I still receive the following error. 

'''
~/anaconda/envs/test/lib/python3.6/site-packages/tensorly/decomposition/robust_decomposition.py in robust_pca(X, mask, tol, reg_E, reg_J, mu_init, mu_max, learning_rate, n_iter_max, random_state, verbose)
     91 
     92         for i in range(T.ndim(X)):
---> 93             J[i] = fold(svd_thresholding(unfold(D, i) + unfold(L[i], i)/mu, reg_J/mu), i, X.shape)
     94 
     95         D = L_x/mu + X - E

~/anaconda/envs/test/lib/python3.6/site-packages/tensorly/tenalg/proximal.py in svd_thresholding(matrix, threshold)
     68     procrustes : procrustes operator
     69     """
---> 70     U, s, V = T.partial_svd(matrix, n_eigenvecs=min(matrix.shape))
     71     return T.dot(U, T.reshape(soft_thresholding(s, threshold), (-1, 1))*V)
     72 

~/anaconda/envs/test/lib/python3.6/site-packages/tensorly/backend/numpy_backend.py in partial_svd(matrix, n_eigenvecs)
    169     if n_eigenvecs is None or n_eigenvecs >= min_dim:
    170         # Default on standard SVD
--> 171         U, S, V = scipy.linalg.svd(matrix)
    172         U, S, V = U[:, :n_eigenvecs], S[:n_eigenvecs], V[:n_eigenvecs, :]
    173         return U, S, V

~/anaconda/envs/test/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py in svd(a, full_matrices, compute_uv, overwrite_a, check_finite, lapack_driver)
    127     # perform decomposition
    128     u, s, v, info = gesXd(a1, compute_uv=compute_uv, lwork=lwork,
--> 129                           full_matrices=full_matrices, overwrite_a=overwrite_a)
    130 
    131     if info > 0:

MemoryError: 
'''

**Comment by JeanKossaifi** [comment]
It seems to be a memory issue -- this particular method relies on SVD.
Can you run it on a machine with more RAM?
Alternatively, we could try to change the svd-thresholding to not compute all the eigenvalues (e.g. by setting the tolerance adequately in the sparse svd).

**Comment by rtmatx** [comment]
Thanks a lot. I will pull the new code and will update you on the status

**Comment by JeanKossaifi** [comment]
@rtmatx, did it solve your issue?

**Comment by JeanKossaifi** [comment]
Just checking whether this is solved? If so, will close the issue.

**Comment by rtmatx** [comment]
I am extremely sorry for late reply. The issue has been resolved with the new update.

**Comment by JeanKossaifi** [comment]
Glad to hear! :)
