### ISSUE TITLE
Can tensor decomposition use the information of time order?

### ISSUE THREAD

**Issue by wanglu2014** [tensorly/tensorly#370]
In CP decomposition, the order of time point (1,2,3 or 1,3,2) have no influence on the result. Is there a way to use time order information?

**Comment by wanglu2014** [comment]
Thank you for your suggestion. I have tried with parafac, after changing the time order of input data, the result has dramatically changed as you said. However, I do not understand the reason how time order influences decomposition. if you can provide an intuitive explanation, it will be great helpful.

**Comment by JeanKossaifi** [comment]
To apply PCA to a spatio-temporal volume you'd need to first flatten it while with tensor decomposition, one of the modes will correspond to the time so you can disentangle the modes of variation. 

For a good intro to tensor decomposition and CP in particular, I recommend the excellent survey by Kolda and Bader, ["Tensor Decompositions and Applications"](https://www.kolda.net/publication/TensorReview.pdf). You can also check our [user guide](http://tensorly.org/dev/user_guide/index.html) and [examples](http://tensorly.org/dev/auto_examples/index.html).

Hope this helps.

**Comment by wanglu2014** [comment]
Thank you for your reply!
