### ISSUE TITLE
How to evaluate the error value returned by parafac?

### ISSUE THREAD

**Issue by wanglu2014** [tensorly/tensorly#374]
How much error is too much for a tensor decomposition? Thank you for your attention!
My code is 
tenout,err = parafac(X, rank=2,return_errors=True)
returned errors is:
Out[1]: 
[0.9132949846975736,
 0.9106341750244371,
 0.9099095836773052,
 0.9096668682254115,
 0.909570677979538,
 0.9095252587431448,
 0.9095006505001352,
 0.9094860276925021,
 0.9094768196226811,
 0.9094708049108392,
 0.909466779544832,
 0.9094640391626648,
 0.9094621498394916,
 0.9094608345424097,
 0.9094599118030493,
 0.9094592604385652,
 0.9094587983045211,
 0.9094584690523205,
 0.9094582336542332,
 0.9094580648645127,
 0.9094579435373832,
 0.9094578561449852,
 0.9094577930847157,
 0.909457747513632,
 0.9094577145391936,
 0.9094576906534855,
 0.9094576733353096,
 0.9094576607689197,
 0.9094576516443343]

The distribution of input data was like that
![图片](https://user-images.githubusercontent.com/12541282/154213428-746b4b1e-7673-4886-a85d-f0bfc7cd9c00.png)

**Comment by JeanKossaifi** [comment]
It depends on the application really. However, you may want to check the relative reconstruction error (`tl.norm(reconstruction - tensor)/tl.norm(tensor)`), which can be more informative.
