### ISSUE TITLE
How to reconstruct 2d matrix of each pair of dimensions from the result of parafac2?

### ISSUE THREAD

**Issue by wanglu2014** [tensorly/tensorly#383]
parafac2_to_slices can reconstruct the slices of one dimension. How to reconstruct 2d matrix for each pair of factors from the result of parafac2, just like parafac?

**Comment by JeanKossaifi** [comment]
@MarieRoald @yngvem are the Parafac2 experts :)

**Comment by MarieRoald** [comment]
I don't quite understand what you mean here. Do you want slices in different modes? In that case, you should use the ``parafac2_to_tensor`` function, which constructs a dense tensor from the PARAFAC2 decomposition (if it is a ragged tensor, then each slice is padded by zeros at the end to ensure that they all have equal shape). Here is an example:

```python
import tensorly as tl
from tensorly.random import random_parafac2

I, J, K = 20, 30, 40
R = 5
pf2 = random_parafac2([(J, K) for i in range(I)], R)

X = tl.parafac2_tensor.parafac2_to_tensor(pf2)
horizontal_slice = X[0]
lateral_slice = X[:, 0]
frontal_slice = X[:, :, 0]

print(X.shape)
print(horizontal_slice.shape)
print(lateral_slice.shape)
print(frontal_slice.shape)
```
```raw
(20, 30, 40)
(30, 40)
(20, 40)
(20, 30)
```

**Comment by wanglu2014** [comment]
> I don't quite understand what you mean here. Do you want slices in different modes? In that case, you should use the `parafac2_to_tensor` function, which constructs a dense tensor from the PARAFAC2 decomposition (if it is a ragged tensor, then each slice is padded by zeros at the end to ensure that they all have equal shape). Here is an example:
> 
> ```python
> import tensorly as tl
> from tensorly.random import random_parafac2
> 
> I, J, K = 20, 30, 40
> R = 5
> pf2 = random_parafac2([(J, K) for i in range(I)], R)
> 
> X = tl.parafac2_tensor.parafac2_to_tensor(pf2)
> horizontal_slice = X[0]
> lateral_slice = X[:, 0]
> frontal_slice = X[:, :, 0]
> 
> print(X.shape)
> print(horizontal_slice.shape)
> print(lateral_slice.shape)
> print(frontal_slice.shape)
> ```
> 
> ```
> (20, 30, 40)
> (30, 40)
> (20, 40)
> (20, 30)
> `

Thank you for your reply. I mean the factors decomposited by CP decomposition, can be used to reconstruct the matrix. Such as the A (n rows, r columns) and B factors (m rows, r columns) in A, B and C factors generated by CP decomposition, can reconstruct the matrix of AB(n rows and m columns).

**Comment by yngvem** [comment]
I am also a bit unsure of what you want. There is, to my understanding, no Khatri-Rao trick with PARAFAC2. With PARAFAC2, each entry of the dataset (tensor or stack of matrices) is composed by `X[i, j, k] = sum(weights * A[i, :] * (P[i] @ B)[j, :] * C[k, :]`. This is what the `parafac2_to_tensor`-function computes, and based on this computation, you can slice out horizontal, lateral and frontal slices as matrices (like @MarieRoald showed above) or use the `unfold`-function for an unfolded tensor.

**Comment by wanglu2014** [comment]
> I am also a bit unsure of what you want. There is, to my understanding, no Khatri-Rao trick with PARAFAC2. With PARAFAC2, each entry of the dataset (tensor or stack of matrices) is composed by `X[i, j, k] = sum(weights * A[i, :] * (P[i] @ B)[j, :] * C[k, :]`. This is what the `parafac2_to_tensor`-function computes, and based on this computation, you can slice out horizontal, lateral and frontal slices as matrices (like @MarieRoald showed above) or use the `unfold`-function for an unfolded tensor.

Thanks!

**Comment by MarieRoald** [comment]
Should we close this, @JeanKossaifi?

**Comment by JeanKossaifi** [comment]
Yes, thanks @MarieRoald and @yngvem!
