### ISSUE TITLE
Numerical constants?

### ISSUE THREAD

**Issue by j6k4m8** [tensorly/tensorly#395]
I wonder if the authors of this project have considered adding numerical constants (π, e) to the library.

#### Argument in favor

Right now, as an author of another developer-facing library, I can remain un-opinionated about my users' backend of choice when using functions:

```python
import tensorly as tl

tl.log(tl.tensor(...))
```

But as soon as I want to include numerical constants, I have to pull them from a specific library:

```python
import tensorly as tl
import numpy as np

tl.log(np.e ** tl.tensor(...))
#      ^^^^
```

This means that I can't operate on numerical constants without also having a backend library as a dependency for my library. Adding these constants to tensorly would mitigate this.

#### Argument against

Adding these constants might mean that certain operations will return unexpected results if there are tiny differences between backends' definitions of the constants. For example,

```python
tl.pi - np.pi
```

might be nonzero, if `tl.pi` uses a definition from another library.

-----

Curious to hear your thoughts on this!

**Comment by JeanKossaifi** [comment]
I'm happy to add new functions to the backend if there's a need / usecase for them. As you say, the whole point is to enable users to abstract away which array library actually runs the code.
