### ISSUE TITLE
Flake8 / Black lint for the codebase?

### ISSUE THREAD

**Issue by j6k4m8** [tensorly/tensorly#399]
#### Is your feature request related to a problem? Please describe.
While writing #398 I had to adjust to a few different file styles across the codebase. Like mentioned in #76, I think it would be super useful to have an enforced styleguide like `black` or `flake8` (with a slight personal preference for black!) for new users to be able to contribute:
* A single-command tool to automatically format files when they're written (e.g., running `black ./path/to/this/codebase`)
* A pull-request check to make sure the code passes styleguide before it can be merged to master (quite easy through the same github actions already in use)
* Documentation for new developers to easily get started with compliant code style in their contributions

I'd be happy to set up all of the above but it would likely make some big changes to the codebase and it's not my place to make such enormous changes without checking with core maintainers :) 

Really enjoying getting to use this for a lot of my upcoming projects, thank you for welcoming my contributions so far @JeanKossaifi :)

**Comment by JeanKossaifi** [comment]
Agreed, over time we got a little lax with pep8 and it's easy to miss some of those issues in a PR. I also have a preference for `black` over just `pep8`, happy to have a PR to add it to the CI !

It's great to have you onboard @j6k4m8!

**Comment by j6k4m8** [comment]
Super awesome, I will submit a PR shortly! Glad to be able to contribute :)
