### ISSUE TITLE
Implementation of tensor PLS

### ISSUE THREAD

**Issue by aarmey** [tensorly/tensorly#416]
#### Is your feature request related to a problem? Please describe.

This is just a note that @cyrillustan and @JacksonLChin will be working on an implementation of tensor PLS over the summer.

#### Describe the solution you'd like

We'll open a PR of this with some testing. One question is whether this should go into the regression module, or somewhere else. For example, scikit-learn has a module called cross_decomposition...

#### Describe alternatives you've considered

There don't seem to be alternative implementations in Python.

#### Additional context

We plan to use this, and then extend it to using PLS with coupled tensors as X. The latter method won't be as generally useful, so we will leave that out of the PR.

**Comment by JeanKossaifi** [comment]
Awesome, it's something I've been quite interested in, looking forward to it!

**Comment by cohenjer** [comment]
As far as I am concerned, PLS (if you mean partial least squares) should be in the regression module. In Rasmus Bro's thesis, he refers to PLS as Partial Least Squares regression.
