### ISSUE TITLE
Replace `assert_almost_equal` with `assert_allclose`

### ISSUE THREAD

**Issue by MarieRoald** [tensorly/tensorly#426]
`assert_allclose` was added to TensorLy in #420 and `assert_almost_equal` (which is currently used in many tests in TensorLy) is discouraged by [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_almost_equal.html). We should therefore update all tests that use `assert_almost_equal` to use `assert_allclose` instead.

The change should be relatively straightforward: Find a test with `assert_almost_equal`, and change to `assert_allclose`, possibly modifying the tolerance accordingly.

**Comment by bakhtos** [comment]
I see that no one replied to this Issue yet, so I am going to look into it soon :)
(Although I need some hint to understand how to convert between tolerance parameters of these two functions...)

**Comment by aarmey** [comment]
I don't see any more instances of `assert_almost_equal`, so I think this has been fixed.
