### ISSUE TITLE
TRL Function Issue

### ISSUE THREAD

**Issue by Alan7771** [tensorly/tensorly#428]
#### Describe the bug
 
Hello, 

I am experiencing an Issue with the TRL function code from the 

[tensorly-notebooks](https://github.com/JeanKossaifi/tensorly-notebooks)/[05_pytorch_backend](https://github.com/JeanKossaifi/tensorly-notebooks/tree/master/05_pytorch_backend)/tensor_regression_layer_pytorch.ipynb 

When I follow the notebook everything seems to be working at first glance, but upon further inspection I saw that the TRL layer did not have any weights generated when I tried to print a model summary. Then I noticed the “ Fix This in the TRL Class block. Can some one please explain what that means and if It has something to do with the TRL layer not having any weights. 

Thank you for your time and help,

Stay safe, Alan Urteaga

**Comment by JeanKossaifi** [comment]
Hi @Alan7771 - it is possible the function you use to print the summary just isn't showing the weights but they should be there. The "FIX THIS" comment pertain to the way I initialize the weights in the example, not the module itself.

Either way, you should use [TensorLy-Torch](http://tensorly.org/torch/dev/index.html): it provides out-of-the-box tensorized layers and is much more advanced than the example notebook. In particular,[ TRL is provided natively](http://tensorly.org/torch/dev/modules/generated/tltorch.factorized_layers.TRL.html#tltorch.factorized_layers.TRL). Feel free to reopen an issue there if this doesn't solve it, closing this as it isn't directly related to TensorLy itself.
