### ISSUE TITLE
tensorly on large-scale tensor?

### ISSUE THREAD

**Issue by devnkong** [tensorly/tensorly#431]
Hi team,

Thanks for this nice repo!

I'm wondering if tensorly actually supports decomposition on large tensors? I'm trying to run parafac on a (N,N,2) tensor, N is as large as 10k. It can run with rank 2, but more than that I won't have enough memory. Is it because of tensorly does all the computation in the dense format so it is hard to scale up? Any thoughts on how I can run parafac on large tensors? Thanks!

**Comment by JeanKossaifi** [comment]
@devnkong did this resolve your issue?

**Comment by devnkong** [comment]
Hey guys, it works now, thanks!
