### ISSUE TITLE
Backend-specific functions

### ISSUE THREAD

**Issue by yngvem** [tensorly/tensorly#432]
@MarieRoald and I have been thinking about how to implement backend-specific functions in TensorLy. We've currently settled on a decorator as a good approach. Here's a draft of the API we're imagining

```python
def _numpy_func(x):
    return 2


@register_backend_specific('numpy', _numpy_func)
def func(x):
    return x

tl.set_backend("pytorch")
print(func(5))
tl.set_backend("numpy")
print(func(5))
```
```
5
2
```

We also have a skeleton implementation of the decorator:

```python
from functools import wraps
import tensorly as tl

def register_backend_specific(backend, backend_func):
    def wrapper(f):
        @wraps(f)
        def wrapped(*args, **kwargs):
            if tl.get_backend() == backend:
                return backend_func(*args, **kwargs)
            return f(*args, **kwargs)
        return wrapped
    return wrapper
```

But, there are also some things to consider:

 1. How do we ensure that the backend-specific functions are properly documented?
 2. What (if any) changes to the function signature should we accept?

Currently, @MarieRoald and I have landed on not allowing any changes to the signature as the answer to both questions. If an argument is only supported by one backend, then that should be explicitly handled by all implementations, and an appropriate exception should be raised for those that do not support it. This way we ensure that there are no "hidden" features in the backend-specific functions that aren't shown in the docstrings or function signature.

What do you think @JeanKossaifi @aarmey @cohenjer @caglayantuna?

**Comment by JeanKossaifi** [comment]
@yngvem @MarieRoald -- I really like it!

Currently I essentially have been relying on a backend system (both for the actual backend and the `tenalg` module). 
I guess the general theme here is that we make the method dynamically dispatchable. The only concern (both for the backend, tenalg backend and this) is the overhead of doing the fetching each time. 

I've tried to do all the backend related "work" once only, when the backend is first set. The rest becomes just a lookup. I wonder if we could use some (optimized?) implementation, e.g. [singledispatch](https://docs.python.org/3.4/library/functools.html#functools.singledispatch) or the more general version [multipledispatch](https://github.com/mrocklin/multipledispatch) (which is not in the stdlib).

**Comment by aarmey** [comment]
This is outside my expertise but seems reasonable. I would suggest profiling to see if there is a performance hit, since it could really matter depending on the context. For example, this would probably provide some overhead for something calling `tl.abs()` 100,000 times, while any call to `tl.tenalg.khatri_rao()` is already going to be slow enough to not be affected by dispatch.

**Comment by yngvem** [comment]
I did some testing with the example code above, and the call time went from ~80 ns to ~500 ns. So a big relative change, but still a very small number. The idea was to allow for backend specific functions in cases where the backend system is overkill (for example a sparse-specific CP-error computation). The performance overhead is likely negligible compared to most operations we do (adding two 100 x 100 numpy arrays is 2.8 µs on the same computer and creating an empty 100 x 100 numpy array is 500 ns).

**Comment by JeanKossaifi** [comment]
Yes, I agree with both your points @aarmey and @yngvem - to summarize, there's the performance price of dynamic dispatch, this is something we'd need to handle as efficiently as possible for all backend functions that are called many times. There's also the less performance critical case of functions that are only called a few times.  

In any case, I really like this API, I'm +1 on going ahead with this!
