### ISSUE TITLE
How decompose a large tensor with limited memory?

### ISSUE THREAD

**Issue by wanglu2014** [tensorly/tensorly#433]
Since the tensor is large (2000*2000*2000), we meet a error message since memory limitation. Is there a way to solve this problem, might just like split into batches in neural network?

**Comment by aarmey** [comment]
Hi @wanglu2014—Do you have an idea of where you hit the memory issue? If it is during initialization, then try setting `init="random"` to avoid SVD initialization.

**Comment by JeanKossaifi** [comment]
Going to close, feel free to reopen if random init didn't solve your issue.

**Comment by wanglu2014** [comment]
Thank you for your help. Actually, it has solved this problem in some conditions. However, for extramely large dataset, such as 40000*300*5000 Is there other way to compute it with limited memory?

**Comment by JeanKossaifi** [comment]
Hi @wanglu2014  -- in that case, I recommend you try the [randomized SVD](https://tensorly.org/dev/modules/generated/tensorly.decomposition.RandomizedCP.html#tensorly.decomposition.RandomizedCP) or even a gradient based decomposition, e.g. using [TensorLy-Torch](http://tensorly.org/torch/dev/).
