### ISSUE TITLE
Use walrus operator  `:=` in checks before certain error messages 

### ISSUE THREAD

**Issue by bakhtos** [tensorly/tensorly#439]
While preparing a PR for #427, I noticed that many errors checks that can result in error message have the form

`if foo(tensor) != 1:
print(f"Tensor function returns {foo(tensor)}, should return 1")
`

In this case `foo(tensor)` is evaluated twice - first for the check, secondly for the printout message. Python 3.8 introduced the walrus operator (:=), which can bind a name to an expression for that value to be reused later, to avoid expensive operations (see PEP 572 https://peps.python.org/pep-0572/).

This could allow such checks to be rewritten as 

`if (result := foo(tensor)) != 1:
print(f"Tensor function returns {result}, should return 1")
`

I suggest rewriting certain checks in TensorLy in this fashion and bumping minimum supported version of Python to 3.8

**Comment by bakhtos** [comment]
I can volunteer to solve this issue ofc

**Comment by JeanKossaifi** [comment]
That's a good point but I'm not sure we want that, at least not in most cases: 
* if there is an error and the program is to crash anyway, it's not a big deal to recompute and spend a little more time as generating the Traceback will more likely take more time anyway.
* if not and the program continues to run, we are creating a new variable that will never be used but will potentially take a lot of memory.

**Comment by bakhtos** [comment]
Hello! I understand you comments but I kind of see them in the opposite way
- If the program crashes anyway, whats the point in wasting time recomputing? :) 
- Python uses reference semantics, so we are just creating a new reference, not copying the whole data into that variable. Or do you mean that the memory won't be released because we are keeping a reference to that result even after the check succeeds? If we use the same names for these new variables in all such checks (e.g. `result` or `check`), then we will be reassigning the reference and so old results will eventually be garbage-collected.

**Comment by aarmey** [comment]
We have a good number of users on Python 3.7.
