### ISSUE TITLE
Misleading error messages when verifying user-provided rank

### ISSUE THREAD

**Issue by bakhtos** [tensorly/tensorly#441]
Hello!

I noticed there are several situations when a user might see the following message:

`Provided rank[0] == {} but boundary conditions dictate rank[0] == rank[-1] == 1: setting rank[0] to 1.`

or

`Provided rank[-1] == {} but boundary conditions dictate rank[0] == rank[-1] == 1: setting rank[-1] to 1.`

I seem to have found three places in code that cause this message:

- https://github.com/tensorly/tensorly/blob/main/tensorly/random/base.py#L200
- https://github.com/tensorly/tensorly/blob/main/tensorly/tt_tensor.py#L267
- https://github.com/tensorly/tensorly/blob/main/tensorly/contrib/decomposition/_tt_cross.py#L105

The misleading thing is the fact that message says `setting rank to 1`, however only in one of those cases (in `contrib` ) does this actually happen, and there only for one of the two checks. In other cases this message is actually part of `ValueError` exception.

I believe throwing an error is actually the correct way to handle this, since otherwise user might miss the fact that something has been modified by the program and make incorrect conclusions about the results of the computation.

So should all these messages be conformed to the same style? I.e. raising an error and not mentioning changes to rank?

PS Also notice that these errors also contain many typos - mixing up `rank[0]` and `rank[-1]` both in the message and in what rank is actually inserted, also `boundaring` instead of `boundary` and `dictatate` instead of `dictate`. (The wrong rank index I fixed in the PR #438, but otherwise still needs to be corrected)

**Comment by JeanKossaifi** [comment]
Thanks for spotting @bakhtos, this should be fixed! I agree, it would be safer to raise an issue rather than silently change the rank. Would be great if you wanted to make a PR for this!
