### ISSUE TITLE
TT decomposition syntax and comparison to MPS

### ISSUE THREAD

**Issue by mhelal** [tensorly/tensorly#449]
#### Describe the bug

Hi

I am trying to build a tutorial on TT in tensorly, and I am confused about several classes and functions you provide for it. This would not be a bug. **First**, The following code:

```python
from tensorly.decomposition import TensorTrain
import tensorly as tl

tt = TensorTrain (T1, verbose=True)
tt.fit_transform(T1)

gives the error:
TypeError: __init__() got multiple values for argument 'rank'


The class has rank equal to the tensor content!
tt.rank
array([[[2.44881444, 1.73228502],
        [1.86710023, 1.32793821]],

       [[2.8092765 , 1.96777072],
        [1.39172629, 0.9578477 ]]])
```

**Second**, I could not find an example for using: from tensorly import tt_tensor or tt_matrix

**Third**, the following code worked for me:
```python
from tensorly.decomposition import TensorTrain
import tensorly as tl

tt = TensorTrain (T1, verbose=True)
tt.fit_transform(T1)
```
and 
```python
from tensorly.decomposition import matrix_product_state

rank = list(T1.shape) # full rank : boundaring conditions dictatate rank[0] == rank[-1] == 1: setting rank[0] to 1.
rank[0] = 1
rank.append(1) # boundaring conditions dictatate rank[0] == rank[-1] == 1: setting rank[0] to 1.
factors = matrix_product_state(T1, rank=rank)

[f.shape for f in factors]
```
But they give different decompositions. Here https://tensornetwork.org/mps/ it says they are the same. I reconstructed from both factors using tt_to_tensor, to find that your TT implementation gives a higher RMSE error. I would appreciate it if you shed some light on this. 

**Finally,** I know that you do not have an implementation for tensor rings, but I thought I would ask anyway if you know a good one to give an example on,

Thank you

#### Versions

Windows-10-10.0.22000-SP0
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
NumPy 1.20.0
SciPy 1.7.3
TensorLy 0.7.0

**Comment by cohenjer** [comment]
Hi @mhelal, let me try to help you the best I can, although my own tt usage in tensorly is limited (and the tt support in tensorly is overall very light).

1. I think you need to provide the tt dimensions when creating a tt class instance ? I don't know what is T1 in your example, but I assume this is what happened.
2. You are right as far as I know. We do plan on improving the docs, but we would love to have your input so feel free to make a PR with an example of yours!
3. I think matrix_product_state is deprecated. In the latest version of tensorly is it recommended to only use tensor_train. In principle the two models are the same, but the algorithms may differ. Maybe the new tt implementation gave higher error on a particular example, but you would need to average that over several realisations to conclude that the new code is worse in some sense. I did not implement or follow these changes but if you spot some problem with the current tt implementation do not hesitate to mention it here again.
Note that you may want to clone the repo to have the very latest tensorly version, even though a release should come up pretty soon.
4.  In the repo version of tensorly there is an implementation of Tensor Ring (thanks to @merajhashemi).

**Comment by JeanKossaifi** [comment]
Thanks for opening the issue @mhelal. Regarding the doc, I've just opened #454 to fix those issues. 

As Jeremy mentioned, the matrix_product_state is deprecated, we went for tensor_train as it is more commonly used in ML. However, the MPS actually simply calls tensor_train under the hood so what you are seeing is just several results from running the same algorithm.  If you are using PyTorch you can also have a look at the [TTTensor](http://tensorly.org/torch/dev/modules/generated/tltorch.TTTensor.html#tltorch.TTTensor) class there, it might be more intuitive to use. Finally, for the rank you can either pass the actual rank as a tuple, or a float between 0 and 1 to indicate the fraction of parameters you want to keep.
