### ISSUE TITLE
multiple gpu usage when using torch backend

### ISSUE THREAD

**Issue by larryzhang95** [tensorly/tensorly#457]
I'm enjoying the use of tensorly, especially when sped up with a torch backend. However, I'm wondering if there's support for using multiple GPU's when using the torch backend. I could not find any information about multiple GPU support for this. Some of the tensors I am working with are quite large (e.g. dimension (190,1100,40000)), and when executing CP decomposition I often run into issues with GPU memory allocation, even on A100 GPUs which have 80+ GB of memory. 

I think there may be other solutions that I have not tried, and there may be ways to allocate GPU usage (e.g. distributing imported tensor across multiple GPUs), but I'm personally not familiar with how to do this.

Having built in support for this would be amazing, since the torch backend saves me so much time (moving from days on CPU to minutes on GPU), but limits the size of tensors I can perform decomposition on.

**Comment by JeanKossaifi** [comment]
Thanks for the kind words @larryzhang95. Unfortunately it is not trivial to do model distribution as opposed to data distribution and I don't see how to immediately add this in a backend agnostic way. 

You may want to have a look at [TensorLy-Torch](http://tensorly.org/torch/dev/) and gradient based decomposition for this but this may not solve your issue either.

**Comment by larryzhang95** [comment]
Unfortunately the tensors are not sparse, lots of time series data.

The issue with model distribution fits my understanding too.

I probably will focus on reducing the complexity of the problem to overcome the issue; the gradient based decomposition sounds interesting, and will look into tltorch. 

Will close out issue - it was worth a shot!
