### ISSUE TITLE
Support generic ndarray interface

### ISSUE THREAD

**Issue by mrocklin** [tensorly/tensorly#47]
Hi all, nice project here.  

I'd like to ask some questions about generalizing these algorithms to other classes that support the numpy.ndarray interface like [dask array](https://dask.pydata.org/en/latest/array.html), [sparse arrays](http://sparse.pydata.org/en/latest/), or [cupy/chainer gpu arrays](https://cupy.chainer.org/).  I have two long term objectives for these questions:

1.  Establish a tensor factorization code that can work in a variety of situations (dense CPU, dense GPU, sparse CPU, distributed dense CPU, distributed sparse CPU, distributed dense GPU)
2.  Improve the state of numpy-style array computing in Python so that it is easier to write code that applies generally to many of these situations.

So objective 1 is a specific case that I hope to use to push on objective 2.  

Looking at the backend mechanism in this library it looks like you've already isolated many of the API points that this project would need from an upstream array library:

1.  ufuncs
2.  tensordot
3.  einsum
4.  svd
5.  slicing
6.  ... (what am I missing?)

However I suspect that, even if we're able to make things produce accurate results, that there are likely to be cases in the tensorly codebase where performance suffers due to how things are written not being well optimized for certain data structures.  

Some general questions for tensorly maintainers

1.  Are there any situations in the tensorly codebase that you think might be problematic when extending to sparse or distributed arrays where the performance profile may change (the relative costs of different operations may change significantly)
2.  Is altering tensorly to make these other data layouts effiicient in-scope for the project?
3.  Are there other concerns that you anticipate?

To be clear, my personal objective is to support these use cases without making several other backend wrappers.  Ideally we evolve numpy to the point where that single backend file suffices for any project that looks sufficiently like a numpy array.

cc 

-  @njsmith @stefanv for numpy
-  @hameerabbasi for sparse
-  @jcrist for dask array
-  @datametrician for GPUs (please forward to relevant cupy devs, I unfortunately don't know who to ping here)

Comment to those cc'ed above.  We've all spoken about pushing on the generic ndarray interface.  Tensor factorization seems like a nice case study where many of the ndarray projects would be relevant.

**Comment by hameerabbasi** [comment]
I'd love to see this in action. An example use-case:

Last year, I was working on [rescal.py](https://github.com/mnick/rescal.py), which is a tensor learning algorithm that absolutely _needs_ sparse arrays to be of any use in a problem of any scale. It also needs a 3-D representation, so it can be thought of as a tensor factorization problem.

It (unfortunately) uses lists of `scipy.sparse.csr_matrix`, and while it works well in this context, it isn't optimal.

Anyway, my first task was to use projections (which didn't work) to scale this up, and my second instinct (now) is to rewrite it to use Dask with pydata/sparse (still needs `np.solve`). (Distributed sparse arrays for those following this)

**Comment by JeanKossaifi** [comment]
Hi @mrocklin!

Thanks for the kind words and the interest! These considerations are the reason behind the backend system of TensorLy. 

NumPy is an amazing library, with a tested and proven API. As such, I believe the way forward lies in having a shared basic (ndarray) interface. However, this is yet to be the case and I had to introduce the backend system to provide TensorLy with that shared interface. 

 I did try to make the set of required functions as lean as possible and it should be trivial to add a new backend provided this respects the NumPy conventions. As a proof I just added a CuPy backend :)

I am happy to make changes to TensorLy to enable functionalities such as sparse tensor. My main aim in doing is to ensure that the code and API remain as simple as possible for users and devs. I do think that some parts may break when adding sparse tensors (e.g. sparse tensors will not be supported by all backend and/or by all functions). However, I do want to see sparse tensor support in TensorLy. 

The easiest way, for now, might be to add a `contrib` submodule where we could break partially compatibility with the rest. This would also allow to write some sparse only functions.

**Comment by mrocklin** [comment]
> As such, I believe the way forward lies in having a shared basic (ndarray) interface. However, this is yet to be the case and I had to introduce the backend system to provide TensorLy with that shared interface.

Understood.  What I'm suggesting here is that we use TensorLy as a case study to push requirements upstream to NumPy.  I believe that they are amenable to this and at a good stage to evolve right now.

> As a proof I just added a CuPy backend :)

Very cool!  It's awesome how easy that was.  I'm curious, do you have thoughts on what would have needed to change within CuPy and NumPy to make your explicit cupy backend unnecessary?  I think that a list of necessary changes in both libraries would be a valuable thing to produce here, possibly even as valuable as the CuPy backend to TensorLy itself.  There seems to be some momentum to unify around these APIs and so I think that a little bit of information from libraries like this one can help to steer that effort. 

> I do think that some parts may break when adding sparse tensors (e.g. sparse tensors will not be supported by all backend and/or by all functions).

Similarly, how do you think things would break?  What operations would sparse arrays need to support well?  Or are you concerned that the algorithms within TensorLy might not be ideal for sparse arrays generally and that entirely new algorithms may be better (for example, to avoid filling in sparse arrays).

**Comment by JeanKossaifi** [comment]
Support for CuPy was very easy to add as it mostly works as a drop-in replacement for NumPy.

Aside from the obvious, issues arise from things like:
- slight differences in methods and parameter names (e.g. dim instead of axis) --not really an issue with CuPy
- differences in algorithms (e.g. SVD crashing on large matrices)
- differences in the way context is handles (e.g. tensor.cuda(), ctx=mxnet.cpu(), for device, or np.float32 vs "float32" vs torch.float32, etc)
- lack of handling of 0-order tensors

I actually wrote a [short blog](http://jeankossaifi.com/blog/deep-learning-framework.html) on this topic regarding such considerations when building a tensor/deep learning framework.

**Comment by JeanKossaifi** [comment]
Currently done by subclassing the Backend class #95

**Comment by jakirkham** [comment]
@JeanKossaifi, are you familiar with [NEP 18]( https://www.numpy.org/neps/nep-0018-array-function-protocol.html )?
