### ISSUE TITLE
Fetch Kinetic dataset

### ISSUE THREAD

**Issue by JeanKossaifi** [tensorly/tensorly#475]
Temporarily skipping the test for the [Kinetic dataset](https://github.com/tensorly/tensorly/blob/8ff7e2950ca939c64641bfe0169e455f7cc59b56/tensorly/datasets/data_imports.py#L856) - the download link and data format seem to have changed. 

https://github.com/tensorly/tensorly/blob/8ff7e2950ca939c64641bfe0169e455f7cc59b56/tensorly/datasets/tests/test_imports.py#L42

**Comment by Kuo-TingKai** [comment]
Which dataset?

**Comment by JeanKossaifi** [comment]
Kinetic: https://github.com/tensorly/tensorly/blob/8ff7e2950ca939c64641bfe0169e455f7cc59b56/tensorly/datasets/data_imports.py#L856

**Comment by cohenjer** [comment]
Indeed after 20 years of almost no change, apparently Rasmus Bro's group have a completely new website ^^

I will look into that.

**Comment by cohenjer** [comment]
Update: here is a response from Rasmus Bro about sharing the dataset on the repo directly:
'' You can do whatever you like. We do appreciate if you acknowledge where you got it from – that’s a nice gesture.''

So I suggest we share the dataset locally like the other ones. I will make the PR.
