### ISSUE TITLE
cp_permute_factors() sometimes return the wrong permutation

### ISSUE THREAD

**Issue by maximeguillaud** [tensorly/tensorly#487]
#### Describe the bug
cp_permute_factors() sometimes returns a wrong result due to a flawed definition of the cosine distance for tensors.
Currently, the cosines are added algebraically across the tensor modes, which is wrong. For instance, tensors can have fully colinear factors yielding cosines +1 and -1 in two modes. These cosines cancel out when taking the algebraic sum. The sum across the modes should probably be computed over the absolute values of the cosines.

The sum I am referring to is computed implicitly through the concatenation operation here and the subsequent inner product:
https://github.com/tensorly/tensorly/blob/e5dd2840207e019e1aece7e91928324af0a7857b/tensorly/cp_tensor.py#L680

#### Steps or Code to Reproduce

```
from tensorly.random import random_cp
from tensorly.cp_tensor import cp_permute_factors, cp_to_tensor
shape = (3, 4, 5)
rank = 4
cp_tensor_1 = random_cp(shape, rank, random_state = 0)
cp_tensor_2 = cp_tensor_1.cp_copy()
col_order_2 = [3, 1, 2, 0]
for f in range(3):
    cp_tensor_2.factors[f] = cp_tensor_1.factors[f][:, col_order_2]*(-1)**(f+1)
cp_tensors, permutation = cp_permute_factors(cp_tensor_1, cp_tensor_2)
```
Note that here, in addition to the permutation, factors for modes 0 and 2 are multiplied with -1 to yield cp_tensor_2.

#### Expected behavior

permutation should be equal to col_order_2, i.e.  [3, 1, 2, 0]

#### Actual result

permutation is equal to [2, 1, 3, 0]

#### Versions
Linux-6.1.0-1006-oem-x86_64-with-glibc2.35
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
NumPy 1.24.2
SciPy 1.10.0
TensorLy 0.8.0

**Comment by cohenjer** [comment]
Hi @maximeguillaud, you are right. The best way to do that would be to take the product of the absolute values of the cosines. Feel free to make a small PR to change that if you can!

**Comment by yngvem** [comment]
This is actually already implemented in [TensorLy-Viz](http://tensorly.org/viz/stable/). We should probably migrate some of that functionality over here and add more links to it in the documentation.

@MarieRoald and I could do it, but that would have to wait until we have some spare time again.

**Comment by maximeguillaud** [comment]
> Feel free to make a small PR to change that if you can!

@cohenjer it looks like the fix would involve changing the interface of the `congruence_coefficient` function, and I'm afraid of breaking something by doing this. I would rather leave that to someone more experienced with the tensorly codebase.

**Comment by cohenjer** [comment]
> > Feel free to make a small PR to change that if you can!
> 
> @cohenjer it looks like the fix would involve changing the interface of the `congruence_coefficient` function, and I'm afraid of breaking something by doing this. I would rather leave that to someone more experienced with the tensorly codebase.

No worries, thanks for raising the issue!

**Comment by cohenjer** [comment]
@yngvem that would be ideal indeed, but in the meantime, I can work on a hotfix for the `cp_permute_factors function`, it should be reasonably straightforward.

**Comment by cohenjer** [comment]
Issue should be fixed now, closing !
