### ISSUE TITLE
v0.8.0 installation from pypi fails when importing tensorly but from github it doesn't

### ISSUE THREAD

**Issue by earmingol** [tensorly/tensorly#488]
Hi!

I tried installing tensorly with `pip install tensorly` to install the latest version. After installing it and trying to use it, it fails with the import (see error).
![Screen Shot 2023-02-17 at 15 53 27](https://user-images.githubusercontent.com/12451195/219818302-5f431776-b6b5-42a6-88f0-58420ab325cc.png)

It looks like something is wrong with the build in PYPI because when I try `pip install git+https://github.com/tensorly/tensorly` to install the latest version, everything works perfectly.

**Comment by JeanKossaifi** [comment]
Thanks for reporting @earmingol !

Weird, was this an error fixed since? 
If so we can just push a minor release.

**Comment by earmingol** [comment]
I tried installing it again and I didn't replicate the error, so it looks like it is fixed somehow. The error I had was with python 3.7 on a macbook pro mid-2015 with macOS Catalina.

**Comment by earmingol** [comment]
I'm reopening this issue because I'm getting the error again. I didn't replicate the error in the prior test because I didn't notice I was using the environment with the github installation.

**Comment by JeanKossaifi** [comment]
Thanks @earmingol for tracking this and making the issue! I made a [minor release](https://pypi.org/project/tensorly/), hopefully that fixes it!

**Comment by earmingol** [comment]
@JeanKossaifi this fixed the issue! Thanks! :)
