### ISSUE TITLE
Would it be possible to do a non-negative partial Tucker factorization?

### ISSUE THREAD

**Issue by MelanieN** [tensorly/tensorly#498]
#### Is your feature request related to a problem? Please describe.

I have non-negative data and only want to decompose wrt one mode.

#### Describe the solution you'd like
A combined algorithm on nn Tucker and partial Tucker 

#### Describe alternatives you've considered
Trying to combine them myself

**Comment by JeanKossaifi** [comment]
Thanks @cohenjer.  I think @MelanieN refers to the [partial_tucker](http://tensorly.org/stable/modules/generated/tensorly.decomposition.partial_tucker.html#tensorly.decomposition.partial_tucker) in which case we don't have any projection matrix at all along some of the modes.

We could use a full Tucker along with a `skip_mode` param and create a (fixed) identity for that mode though ideally we'd just want to make an NN `partial_tucker` and completely skip computation along the skip modes.

**Comment by cohenjer** [comment]
@JeanKossaifi I see, sorry I misunderstood the issue. I don't ever use partial Tucker :)

We could definitively implement a partial nonnegative Tucker. I am working on nonnegative Tucker these days, so I might first add a skip_mode option at first; if I find the time I will also do the nonnegative_partial_tucker.

**Comment by JeanKossaifi** [comment]
Awesome! As a side note, going the other way _may_ be easier: tucker is just `partial_tucker` with no skipped mode. 
Typically the main difference would just be when unfolding the tensor along the modes to optimize, we just have this skipped mode: 
```latex
X_[n] = U_n * Core_[n] x_{i=1...n, i != n, i not in skiped_mode} U_i
```

**Comment by JeanKossaifi** [comment]
@MelanieN did this work for you?

**Comment by JeanKossaifi** [comment]
Closing as inactive.
