### ISSUE TITLE
tucker-2 decomposition

### ISSUE THREAD

**Issue by BryantLJ** [tensorly/tensorly#5]
i  was wondering that how to apply a tucker-2 decomposition using tensorly? it seems that it only supports for standard Tucker-Decomposition, anyone can help me?

**Comment by JeanKossaifi** [comment]
Which method do you refer to, can you provide a corresponding paper?

Did you mean Tucker decomposition on second order tensors? Or did you maybe mean PARAFAC2 / PARATUCK2?

**Comment by JeanKossaifi** [comment]
Closed due to inactivity.
