### ISSUE TITLE
Optional order parameter in tl.reshape can't be used with PyTorch backend

### ISSUE THREAD

**Issue by OsmanMalik** [tensorly/tensorly#500]
The documentation for tl.reshape mentions an optional parameter `order`. Using this parameter works fine with the Numpy backend, but not with the PyTorch backend. For the latter, it results in a TypeError.

The following code generates the error:
```python
import tensorly as tl
import numpy as np

tl.set_backend('pytorch')
tensor = tl.tensor(np.random.random((10, 10, 10)))
tensor_reshaped = tl.reshape(tensor, (10, 20, 5), order='C')
```

This generates the following error:
```
TypeError: reshape() got an unexpected keyword argument 'order'
```

The code works fine when the `numpy` backend is used instead.

#### Versions
Windows-10-10.0.19045-SP0
Python 3.10.10
NumPy 1.23.5
SciPy 1.10.1
TensorLy 0.8.1
PyTorch 2.0.0

**Comment by JeanKossaifi** [comment]
Hi @OsmanMalik -- yes this is an issue with the way the documentation is built for the backend functions. Ideally we'd need one doc per backend.

The issue here is that PyTorch does not support `order` in the reshape. Why do you need it for? 
If you absolutely need a reshape with the `order` keyword in Pytorch you'd have to use a combination of transpose and reshapes which most likely would be inefficient.

**Comment by OsmanMalik** [comment]
Hi @JeanKossaifi, I'm implementing an ALS-based function for tensor ring decomposition and was converting over code I had previously written in Matlab. Since Matlab uses Fortran ordering, I'm using `order="F"` to get similar behavior in Python. But I should be able to rewrite the code to avoid using the `order` parameter and just stick to standard ordering, which will probably be more efficient anyway.

**Comment by JeanKossaifi** [comment]
Indeed @OsmanMalik if you're planning to run things on GPU it would be much more efficient to stick with C ordering. I had written a [blog post](http://jeankossaifi.com/blog/unfolding.html) on this, and a [Stack-Overflow post](https://stackoverflow.com/a/50086319/4802196), if this helps. Happy to help adapt the formulas if you need! 

As a side note, would love to have the ALS-TR in TensorLy if you're interested in opening a PR when you're done! :)

**Comment by OsmanMalik** [comment]
Thank you @JeanKossaifi for sharing that blog post. I was wondering about the ordering of unfolding in TensorLy, and this explains it very well. 

I will open a PR when the implementation is done.
