### ISSUE TITLE
Tensor regression with `y` of arbitrary order

### ISSUE THREAD

**Issue by outlace** [tensorly/tensorly#51]
Right now using something like 
```python
estimator = TuckerRegressor(weight_ranks=[5], tol=10e-7, n_iter_max=100, reg_W=1, verbose=0)
estimator.fit(X,y)
```
demands that `X` be of dimensions (num_samples, num_features) and `y` be of dimension (num_samples). Why can't X and y be arbitrary tensor dimensions? For example, if I want to find a weight tensor that will minimize the error between an image (num_images, width, height, channels) and  its rotated version (num_images, width, height, channels), it doesn't appear I can do that with the tensor regression API. Or if I want to learn a tensor that will contract with a vector to produce some simple 2d image (i.e. a matrix).

**Comment by JeanKossaifi** [comment]
X can be a tensor of any order, while y is the vector of output labels. Note that you must have `len(weight_ranks) = ndim(X)` (i.e. the rank of the core tensor).
You can refer to the [user_guide](http://tensorly.org/stable/user_guide/tensor_regression.html), the [documentation](http://tensorly.org/stable/modules/generated/tensorly.regression.tucker_regression.TuckerRegressor.html#tensorly.regression.tucker_regression.TuckerRegressor) and the [example](http://tensorly.org/stable/auto_examples/regression/plot_tucker_regression.html#sphx-glr-auto-examples-regression-plot-tucker-regression-py). 

You can also find the details on the method in the paper "Tensor Learning for Regression", by W. Guo, I. Kotsia, and I. Patras, in IEEE Transactions on Image Processing, 2012.


 I am also working on a more general model to have `y` be of any order but this isn't in TensorLy yet.

**Comment by outlace** [comment]
@JeanKossaifi Thanks for the clarification. I will keep a look out for the update that will low `y` to be any order.

**Comment by kevin-w-li** [comment]
Really NEED THIS!

**Comment by JeanKossaifi** [comment]
I am completely busy the coming month so I don't think I'll have any bandwidth to work on this for a few weeks. Is anyone interested in having a try?

Extending y_i from scalar to vector is fairly straightforward, especially for tensor regression with CP weights.
