### ISSUE TITLE
Can I impute data using Tucker or CP Decomposition for categorical data?

### ISSUE THREAD

**Issue by dohyun-kim92** [tensorly/tensorly#512]
#### Is your feature request related to a problem? Please describe.

I want to correct for missing values using Tucker or CP decomposition in data containing categorical data.

#### Describe the solution you'd like

for example
tensor = np.array([
     [[10, 'red', 'blue'], [30, 'green', np.nan]],
     [[40, 'blue', 'yellow'], [50, np.nan, 'red']],
     [[np.nan, 'green', 'yellow'], [70, 'blue', np.nan]]
]), I want to impute the nan values.
Although data can be imputed with multiple values like Simple imputer, I would like to meaningfully impute categorical data using tensors.

#### Describe alternatives you've considered

If you tell me which functions we can utilize, I will try to combine them.

**Comment by aarmey** [comment]
Hi @dohyun-kim92—CP and Tucker are models for representing tensors of continuous quantities. Is there a reason you think they might be a good match for your problem?
