### ISSUE TITLE
make_svd_non_negative only returns the updated U matrix

### ISSUE THREAD

**Issue by hello-fri-end** [tensorly/tensorly#515]
#### Describe the bug
I'm not sure if this is a bug or if this is actually how this function is supposed to behave but currently, it only returns the updated U value. Incase it's not a bug, I don't understand why the H matrix is computed in this function (https://github.com/tensorly/tensorly/blob/6c7ecfbfbfc088cb1a423e6a5970e19565844651/tensorly/tenalg/svd.py#L65)

Looking forward to your response.

**Comment by JeanKossaifi** [comment]
That's a good point @hello-fri-end, thanks for reporting.
@aarmey should we return H or just not compute it?

**Comment by aarmey** [comment]
Good catch!

`svd_interface()` uses this, and returns the full SVD solution, so this should be returned and used there. I missed it because PARAFAC only uses the left eigenvectors, but it is clear that the SVD methods have found wider interest.
