### ISSUE TITLE
All nan in matrix come from non negative tucker decomposition

### ISSUE THREAD

**Issue by hahia** [tensorly/tensorly#516]
Code:
```
from tensorly.decomposition import non_negative_tucker
tl.set_backend('pytorch')
tensor = tl.tensor(dat, device='cuda:3')
facs_overall = non_negative_tucker(tensor,rank=[8,8, 8],random_state = 2337)
```
dat is
![image](https://github.com/tensorly/tensorly/assets/49113803/ed91a8cf-1e19-486d-815f-3305cba19071)
![image](https://github.com/tensorly/tensorly/assets/49113803/da0b1191-f42c-4217-b8a8-f8f90a3a0a77)
![image](https://github.com/tensorly/tensorly/assets/49113803/842e2838-9b47-4c41-830f-bf36b143c1ae)

The facs_overall
![image](https://github.com/tensorly/tensorly/assets/49113803/1bbd62bc-e538-4615-b1de-222aba70d884)
![image](https://github.com/tensorly/tensorly/assets/49113803/1d0105a5-4363-435f-9125-4dde3ec93d45)

Could someone provide an explanation for this?

**Comment by JeanKossaifi** [comment]
What's your input tensor? Can you produce a minimal snippet of code to reproduce your error? It seems your tensor is very sparse / could it also be low-rank? 

It also seems the range might be problematic - I think that's also link with another thing I want to add in tensorLy: optional normalization of the input tensor (and unnormalizing directly in factorized form) @cohenjer @aarmey 

As a small test, could you try i) lower rank and ii) normalizing your tensor (e.g. remove mean and divide by std).

**Comment by cohenjer** [comment]
Just to complete @JeanKossaifi's great answer, you can easily normalize a tensor `T` using `T = T/tl.norm(T)` but centering would make some values negative in the tensor so I would not do it in the context of nonnegative decomposition.

Something bad which may also occur is if whole slices of the tensor are zero. `non_negative_tucker` is based on multiplicative updates, you may be dividing by zero at some point in the algorithm. There is a safeguard (a small epsilon 1e-12 is added) but maybe with your precision this epsilon is too small and considered 0?

**Comment by JeanKossaifi** [comment]
Closing as inactive.
