### ISSUE TITLE
Init mode == "random" does not return the correct shape in initialize_tucker

### ISSUE THREAD

**Issue by hello-fri-end** [tensorly/tensorly#518]
Modes are not considered when `init` is `random`:
https://github.com/tensorly/tensorly/blob/a982cf962ecc9583a0b54560798ff7db43779440/tensorly/decomposition/_tucker.py#L78-L86

When `init` is random, do we always assume that all modes should be considered? `init` == `svd` allows to initialize along specific modes.

Morever,  in the following test `init` is `svd` while it should be `random`
https://github.com/tensorly/tensorly/blob/main/tensorly/decomposition/tests/test_tucker.py#L59-L64

**Comment by JeanKossaifi** [comment]
You are absolutely right, thanks for highlighting @hello-fri-end! Would be great if you could open a small PR to fix it!

**Comment by hello-fri-end** [comment]
> You are absolutely right, thanks for highlighting @hello-fri-end! Would be great if you could open a small PR to fix it!

Sure, created a PR here to fix the same: https://github.com/tensorly/tensorly/pull/519

**Comment by hello-fri-end** [comment]
Fixed in #519
