### ISSUE TITLE
svd_interface will throw an error if the number of rows of the matrix is smaller than it's columns

### ISSUE THREAD

**Issue by hello-fri-end** [tensorly/tensorly#522]
Let's say, `matrix.shape==(2, 4)` and `n_eigenvecs==3`, `truncated_svd` will output `U.shape ==(2,2)`, `V.shape==(3, 4)` and `S.shape==2`. In this case, `S.diag` in the following line will return a matrix of shape `(2,2)`. The shapes `(2,2), (2,2) and (3,4)` are not compatible for matmul. Ideally, S should be updated as:
`tl.fill_diagonal(tl.eye(U.shape[-1], V.shape[-2]), S)`

https://github.com/tensorly/tensorly/blob/de05e178850eb2abe43ec1a40f80624ca606807d/tensorly/tenalg/svd.py#L428

**Comment by aarmey** [comment]
Fixed in #517
