### ISSUE TITLE
Panel Dataset Time, Company, Feature

### ISSUE THREAD

**Issue by firmai** [tensorly/tensorly#544]
I have a dataset in the following format, what I would love is a decomposition that would allow for a comparison of tickers over time, to decompose all the feature data into a singulr component.

Time, Company, Feature, to Time, Company, Single Component. 

Is that somethig that this library can do?

Thanks in advance :)

**Comment by aarmey** [comment]
Hi @firmai! If you are wanting to decompose just one dimension of your dataset into component patterns, you can just use PCA/SVD. If you flatten time and company into one axis, such that your dataset is time-company x feature, you can then use PCA to derive the component patterns. Your time-company scores can then be reshaped back into time x company x component.

Hope this helps!
