### ISSUE TITLE
Remove MXNet from doc

### ISSUE THREAD

**Issue by JeanKossaifi** [tensorly/tensorly#547]
The website of tensorly still promises MxNet.
<img width="905" alt="Screenshot 2024-01-31 at 13 43 20" src="https://github.com/tensorly/tensorly/assets/68953985/29304ad6-6966-4741-b98a-3686541c8719">

_Originally posted by @bakhtos in https://github.com/tensorly/tensorly/issues/533#issuecomment-1918944246_

**Comment by cohenjer** [comment]
Closing since this has been handled.
