### ISSUE TITLE
Parafac\parafac2 projection 

### ISSUE THREAD

**Issue by natank1** [tensorly/tensorly#552]
let's assume that I train Parafaca or Parafac2  on a tensor A.
Now, let a tensor B that I wish to project on the output of A's decomposition. How do I do it?

**Comment by yngvem** [comment]
This is not a feature request or a bug in tensorly, so I'm closing the issue. You'd do it by fixing one or (typically) more modes to the known values and fitting a new model to the modes you'd like to "project".
