### ISSUE TITLE
OOM issue 

### ISSUE THREAD

**Issue by shuishen112** [tensorly/tensorly#554]
#### Describe the bug
 weights, factors = initialize_cp(
  File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/decomposition/_cp.py", line 76, in initialize_cp
    U, S, _ = svd_interface(
  File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/tenalg/svd.py", line 418, in svd_interface
    U, S, V = svd_fun(matrix, n_eigenvecs=n_eigenvecs, **kwargs)
  File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/tenalg/svd.py", line 226, in truncated_svd
    U, S, V = tl.svd(matrix, full_matrices=full_matrices)
  File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/backend/__init__.py", line 206, in wrapped_backend_method
    return getattr(
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_INVALID_VALUE, when calling `cusolverDnSgesvdj_bufferSize(handle, jobz, econ, m, n, A, lda, S, U, ldu, V, ldv, lwork, params)`. This error may appear if the input matrix contains NaN. If you keep seeing this error, you may use `torch.backends.cuda.preferred_linalg_library()` to try linear algebra operators with other supported backends. See https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.preferred_linalg_library

#### Steps or Code to Reproduce

Please give us a minimal snippet of code to reproduce the issue.

For instance:

```python
import tensorly as tl
import numpy as np
tl.set_backend('pytorch') # Or 'numpy', 'tensorflow', 'cupy' or 'jax'
tensor = tl.tensor(np.arange(7096 * 2048 * 20).reshape((7096, 2048, 20)), device='cuda:0')
# tl.fold(unfolded, mode=0, shape=tensor.shape).shape

from tensorly.decomposition import parafac

factors_cp = parafac(tensor, rank=4,normalize_factors=False)
```

#### Actual result

OutOfMemoryError: CUDA out of memory. Tried to allocate 14.29 GiB. GPU 0 has a total capacty of 39.39 GiB of which 8.25 GiB is free. Including non-PyTorch memory

**Comment by merajhashemi** [comment]
Hi @shuishen112. I can't reproduce the error with the simple example you provided. But looking at the error message using a random initialization should fix your issue.

```diff
- factors_cp = parafac(tensor, rank=4,normalize_factors=False)
+ factors_cp = parafac(tensor, rank=4, init='random', normalize_factors=False)
```

**Comment by shuishen112** [comment]
oh, sorry. the OOM error occurs when I use the following code:

`tensor = tl.tensor(np.arange(7096 * 2048 * 264).reshape((7096, 2048, 264)), device='cuda:0')`

BTY, when I use the A100 with 80G. The error is :

`File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/decomposition/_cp.py", line 338, in parafac
    weights, factors = initialize_cp(
  File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/decomposition/_cp.py", line 76, in initialize_cp
    U, S, _ = svd_interface(
  File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/tenalg/svd.py", line 418, in svd_interface
    U, S, V = svd_fun(matrix, n_eigenvecs=n_eigenvecs, **kwargs)
  File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/tenalg/svd.py", line 226, in truncated_svd
    U, S, V = tl.svd(matrix, full_matrices=full_matrices)
  File "/home/wzm289/miniconda3/envs/lucas_mttl/lib/python3.9/site-packages/tensorly/backend/__init__.py", line 206, in wrapped_backend_method
    return getattr(
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_INVALID_VALUE, when calling `cusolverDnSgesvdj_bufferSize(handle, jobz, econ, m, n, A, lda, S, U, ldu, V, ldv, lwork, params)`. This error may appear if the input matrix contains NaN. If you keep seeing this error, you may use `torch.backends.cuda.preferred_linalg_library()` to try linear algebra operators with other supported backends. See https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.preferred_linalg_library`

**Comment by merajhashemi** [comment]
I still cannot reproduce the error. See the colab below: (it takes a few minutes to run)
https://colab.research.google.com/drive/1K4om-LjhChICjT5nDd22dkmniEf8ILIw?usp=sharing

**Comment by shuishen112** [comment]
> I still cannot reproduce the error. See the colab below: (it takes a few minutes to run) https://colab.research.google.com/drive/1K4om-LjhChICjT5nDd22dkmniEf8ILIw?usp=sharing

Thanks for your quick feedback. Please set the code :

`tensor = tl.tensor(np.arange(7096 * 2048 * 264).reshape((7096, 2048, 264)), device='cuda:0')`

Notably, the shape is [7096 * 2048 * 264].

**Comment by merajhashemi** [comment]
It appears that the error stems from PyTorch's implementation of the SVD algorithm, particularly when dealing with large matrices on the GPU (https://github.com/pytorch/pytorch/issues/102963).
As a potential workaround you could either initialize the decomposition with random factors
```diff
- factors_cp = parafac(tensor, rank=4,normalize_factors=False)
+ factors_cp = parafac(tensor, rank=4, init='random', normalize_factors=False)
```
or use randomized_svd for initialization
 ```diff
- factors_cp = parafac(tensor, rank=4,normalize_factors=False)
+ factors_cp = parafac(tensor, rank=4, svd='randomized_svd', normalize_factors=False)
```
Both work on my machine.

As a side note, you should avoid creating tensors on the CPU with NumPy's default double precision if you're planning to use single precision with PyTorch. Instead, consider creating the tensor directly on the GPU with the desired precision
```diff
- tensor = tl.tensor(np.arange(7096 * 2048 * 264).reshape((7096, 2048, 264)), device='cuda:0')
+ tensor = tl.arange(7096 * 2048 * 264, device='cuda:0').reshape(7096, 2048, 264)
```

**Comment by shuishen112** [comment]
thanks. That make sense
