### ISSUE TITLE
How can I apply activation to each factor matrix?

### ISSUE THREAD

**Issue by SCIKings** [tensorly/tensorly#556]
I want to apply an activation layer to each factor matrix, and then reconstruct the result after activation, and then the resulting result is approximated with the original tensor, so how should I use the library tensorly? For example (tl.decomposition.partial_tucker): w is approximated as f(w1)*f(w2)*f(w3), where f（） denotes the activation function. I would be grateful if you could provide me with some help.

**Comment by JeanKossaifi** [comment]
[TensorLy-Torch](https://github.com/tensorly/torch) provides pytorch based layers and factorizations on top of TensorLy. You can have a look at the hooks we provide (e.g. tensor dropout), you can write a similar hook for the activations you are interested in.

**Comment by JeanKossaifi** [comment]
@SCIKings [TensorLy-Torch](https://github.com/tensorly/torch) provides pytorch based layers and factorizations on top of TensorLy. You can have a look at the hooks we provide (e.g. tensor dropout), you can write a similar hook for the activations you are interested in.
