### ISSUE TITLE
Spiked tensor decomposition

### ISSUE THREAD

**Issue by omarshehab** [tensorly/tensorly#557]
#### Is your feature request related to a problem? Please describe.
I would appreciate an API for spiked tensor decomposition

#### Describe the solution you'd like
I am not aware of any algorithm specifically for spiked tensors

#### Describe alternatives you've considered
Alternating Least Squares (ALS) algorithm

**Comment by JeanKossaifi** [comment]
Hi @omarshehab  - could you expand? Any papers you can link to? Is that something you'd like to open a small PR for?

**Comment by omarshehab** [comment]
> Hi @omarshehab - could you expand? Any papers you can link to? Is that something you'd like to open a small PR for?

This paper contains a number of algorithms for spiked tensor decomposition.

**Comment by omarshehab** [comment]
@JeanKossaifi , by PR, did you mean an implementation by myself?

**Comment by omarshehab** [comment]
@JeanKossaifi , apologies for missing the paper link. https://arxiv.org/abs/1411.1076

**Comment by JeanKossaifi** [comment]
@omarshehab this isn't planned for now - unfortunately I do not have bandwidth but if you are interested in adding it we welcome contributions and would be happy to assist you in opening one!
