### ISSUE TITLE
tensorly version 0.8.0 parafrac does not run on GPU with pytorch backend

### ISSUE THREAD

**Issue by juliadietlmeier** [tensorly/tensorly#561]
I have tensorly 0.8.0 with python 3.9.0. Parafac seems to run on CPU (but crashes due to the memory issues) but does not run on GPU either with the 'pytorch' or the 'numpy' backends. I am working with CP decomposition.

last, first, vertical, horizontal = parafac(layer.weight.data, rank=rank)[1]

where layer=model.conv1 is a layer in my small CNN. The images I am processing are 256x256 pixels

I am sending everything to 'cuda' but still getting the error:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)

Thank you!

**Comment by JeanKossaifi** [comment]
The error says one of your tensors is still on CPU. It may be your input is on CPU.
For deep net applications in PyTorch, it is recommended to use [TensorLy-Torch](https://tensorly.org/torch/dev/) to have this supported out of the box and avoid unexpected issues.

Closing as this is not an error in TensorLY.
