### ISSUE TITLE
Sparse array support

### ISSUE THREAD

**Issue by mrocklin** [tensorly/tensorly#57]
Sparse arrays have been mentioned in a few issues.  Are there concrete plans for this?  

Assuming that no, there are no concrete plans, I'd be inclined to throw [this sparse array](http://sparse.pydata.org/en/latest/) library as a backend and see how well the current algorithms work.  My guess is that things would densify pretty quickly and that sparse-specific algorithms are likely to be necessary, but it might be worth a try.

**Comment by JeanKossaifi** [comment]
Yes, it's worth a try, I'll give it a shot when I get a moment (feel free to open a PR if you want!)
There is a related PR to load sparse tensors - #55

**Comment by JeanKossaifi** [comment]
Added in #77, #84, #84 ...
