### ISSUE TITLE
about unfold

### ISSUE THREAD

**Issue by wll555** [tensorly/tensorly#570]
I don't understand why the unfold function is different from Kolda's. Is there any benefit? If I make a small change to unfold, such as order='F', it becomes Kolda's and my code gives very different results. Sometimes the result is better with unfold, and sometimes the result is better with Kolda's. I don't understand. I am only operating on the unfolding matrix.
Hope to get your answer, thank you.

**Comment by yngvem** [comment]
The unfolding algorithm is dependent on how tensors are stored in RAM. MATLAB is F-contiguous (neighbouring entries in the last dimension is stored next to each other in RAM) by default and Python libraries are typically C-contiguous (neighbouring entries in the first dimension is stored next to each other in RAM).  I. TensorLy, we use C-contiguous arrays which results in the unfolding algorithm we use.

**Comment by JeanKossaifi** [comment]
@wll555 we specify this definition in the documentation and user guide: http://tensorly.org/stable/user_guide/tensor_basics.html

I also wrote a [blog post](http://jeankossaifi.com/blog/unfolding.html) about why it matters when using C-contiguous arrays as @yngvem mentioned. This is especially important on GPU

**Comment by wll555** [comment]
Thank you very sincerely for your answers. I am a beginner in this field, so there are many things I don't understand. Please forgive me for disturbing you. Your blog is very important to me, and I have identified the problem with my code. I used the following formula.

$X=[A,B,C],  X_{(1)}=A(B\odot C)^T$

However, after reading your blog, I realized that when using the unfold function, I should use the following equation.

$X_{(1)}=A(C\odot B)^T$

If I am wrong, I would greatly appreciate it if you pointed it out.
Thank you very much for your answer!

> @wll555 we specify this definition in the documentation and user guide: http://tensorly.org/stable/user_guide/tensor_basics.html
> 
> I also wrote a [blog post](http://jeankossaifi.com/blog/unfolding.html) about why it matters when using C-contiguous arrays as @yngvem mentioned. This is especially important on GPU

**Comment by JeanKossaifi** [comment]
The formulas need to be adapted when you change the definition of unfolding, as I mention in the blog post. You can also check [this paper]( https://arxiv.org/pdf/2107.03436) for more detail, and look directly to our codebase.

**Comment by wll555** [comment]
My code started indexing at 0. At first, I used
 `X0=unfold(X,0)`
and verify
`X0=factors[0]@khatri_rao([factor[2],factors[1]]).T`
But, this is in F-order. Now if I use Tensorly in Python, I should use the following in C-order.
`X0=factors[0]@khatri_rao([factor[1],factors[2]]).T`
I'm curious if there are other formulas that need to be changed, and it would be even better if there is corresponding documentation on how to change these formulas.
If I have made a mistake, please let me know. I will read your code carefully.
Thank you for your response!


> The formulas need to be adapted when you change the definition of unfolding, as I mention in the blog post. You can also check [this paper](https://arxiv.org/pdf/2107.03436) for more detail, and look directly to our codebase.
> 
> Are you starting indexing at 1? If so your first equation should correspond to C indexing and be the correct one. I'd recommend verifying numerically your calculations, see for instance our unit-tests for CP that I believe test what you want:
> 
> https://github.com/tensorly/tensorly/blob/662c4a72cbca0ef881424c94a7615d1538ec5a5c/tensorly/tests/test_cp_tensor.py#L146

**Comment by JeanKossaifi** [comment]
Yes, your code above (the second version) is correct. The C-ordering results in a more natural ordering following the Kronecker product, meaning you no longer need to reverse the ordering in the Khatri-Rao product. I'd recommend directly using our built-in functions for these operations!

**Comment by wll555** [comment]
OK, I will check my code carefully. Again, thank you for your patience and answers.
