### ISSUE TITLE
No pip/conda package for 0.8.2

### ISSUE THREAD

**Issue by f0uriest** [tensorly/tensorly#579]
It looks like the latest release is 0.8.2, but the latest version available on pypi is 0.8.1 which is over a year old and doesn't work with recent versions of JAX, among other things.

**Comment by JeanKossaifi** [comment]
Thanks for opening the issue @f0uriest, indeed we are overdue for a release - I am planning to release one soon, there are a few things we want to finalize first. In the mean time, I'd recommend installing directly from source though, as it's especially easy for TensorLy.

**Comment by JeanKossaifi** [comment]
I just released a new version on pypi, though I'd still recommend installing from sources to get the latest version.
