### ISSUE TITLE
Question on error returning in parafac

### ISSUE THREAD

**Issue by AlexStasik** [tensorly/tensorly#58]
Hi,

in tensorly.decomposition.parafac, it says that the error from each iteration is returned. Is there an inconsistency with the documentation or am I just unable to activate this return?

Thanks a lot for the great project, love tensorly

Best, Alex

**Comment by JeanKossaifi** [comment]
You are right, it doesn't return the errors,  I will fix this. 
Do you have a use case where you need to get the them back? If so we could add a parameter (e.g. `return_errors`) to optionally do so.

**Comment by AlexStasik** [comment]
Hi,
thanks a lot for the quick reply. My use case would be that I want to try out different initialisation values to get best performance and make sure I do not get stuck in a local minimum.

**Comment by JeanKossaifi** [comment]
Want to open a small PR adding a `return_errors` parameters to optionally return a list of the errors?

**Comment by AlexStasik** [comment]
Related question: In the documentation, the weights are also mentioned

    weights : ndarray, optional
        Array of length `rank` of weights for each factor matrix. See the
        `with_weights` keyword attribute.

but never computed. Could you adjust the documentation in this regard?
I can create a pull request if you like or you just change it in the code, whatever you prefer.

**Comment by JeanKossaifi** [comment]
If you want to take a crack at it (correcting the doc + adding a parameter for returning the errors) that's great! :)

**Comment by JeanKossaifi** [comment]
Solved by #59.
