### ISSUE TITLE
Dimensions in partial_tensor_to_vec are sometimes flipped

### ISSUE THREAD

**Issue by jflamant** [tensorly/tensorly#588]
#### Describe the bug
The expected tensor dimensions in ``partial_tensor_to_vec`` appear to be flipped in some situations. I don't know if this is the expected result, but looking at the [API reference](https://tensorly.org/stable/modules/generated/tensorly.base.partial_tensor_to_vec.html#tensorly.base.partial_tensor_to_vec), I wasn't expecting that.  

For instance:
```python
import tensorly as tl
T = tl.randn((2, 3, 4, 5))

print(tl.partial_tensor_to_vec(T, skip_begin=0, skip_end=2).shape)
```
returns ```(6, 5, 4)``` while one could expect ```(6, 4, 5)``` (according to the documentation, the two last dimensions should be left untouched in this case. Is that the expected behavior?

### version
macOS-14.5-arm64-arm-64bit
Python 3.11.1 (main, Dec 21 2022, 18:33:23) [Clang 14.0.0 (clang-1400.0.29.202)]
NumPy 2.0.0
SciPy 1.14.1
TensorLy 0.9.0

**Comment by JeanKossaifi** [comment]
Hi @jflamant - thanks a lot for opening the issue with a snippet to reproduce the issue. I can confirm this is a bug and I can reproduce it, I'll push a fix shortly!
