### ISSUE TITLE
Improve function partial_svd

### ISSUE THREAD

**Issue by chubei** [tensorly/tensorly#6]
In function [partial_svd](https://github.com/tensorly/tensorly/blob/master/tensorly/tenalg/_partial_svd.py#L46), we perform svd which outputs full matrices. IMHO this is not always necessary. Full matrices are not needed under following condition:
`(n_eigenvecs == min_dim)`

I found this issue during performing tucker on a tensor of shape `[3, 3, 1000, 1000]` and rank `[3, 3, 100, 100]`. Without this little modification, this task can't be done on my machine due to lack of memory.

**Comment by JeanKossaifi** [comment]
I agree. I usually only default on partial_svd for testing, so I haven't dealt with this issue.
Would you like make a small pull request with the changes you suggest?

**Comment by chubei** [comment]
PR submitted. I'm new to github. My apologies if anything went wrong.

**Comment by gudovskiy** [comment]
Chubei, thanks for the finding!

**Comment by JeanKossaifi** [comment]
Fixed by #7.
