### ISSUE TITLE
confusing variable names in doc

### ISSUE THREAD

**Issue by sz144** [tensorly/tensorly#62]
If I understand correctly, the variable names `core` and `factors` for the results returned by `tucker` and `non_negative_tucker` functions should be swapped here:
https://github.com/tensorly/tensorly/blob/master/doc/user_guide/quickstart.rst#tensor-decomposition

**Comment by JeanKossaifi** [comment]
You are absolutely right, thanks for flagging!

Would you like to make a small Pull-Request fixing the issue?

**Comment by sz144** [comment]
pull request #63

**Comment by JeanKossaifi** [comment]
Merged, thanks! :)
