### ISSUE TITLE
Does Tensorly with PyTorch backend support variables that require gradient?

### ISSUE THREAD

**Issue by mfaraki** [tensorly/tensorly#66]
Hi,
In an end-to-end deep learning framework with **SGD** optimizer, I'm calling the function "**tucker**" on a 4D tensor (of size **200, 128, 4, 4**)  with pytorch in the backend. The rank parameter is set to **200, 10, 4, 4**. 
I get this error:
RuntimeError: Can't call numpy() on Variable that **requires grad**. Use var.detach().numpy() instead.

It seems that when applying the function **partial_svd** on the mode 1 unfolded tensor,  a conversion to **numpy** matrix is done (that is line 295 in pytorch_backend.py). I'm not sure if that conversion and the related if/else block (from line 279 to the end in pytorch_backend.py).) is necessary because when a rank is not decreased **torch.svd** is called and so should be in this case.

Thanks

**Comment by JeanKossaifi** [comment]
Thanks for reporting. 4d249728ee1f4465dee470011119691a9b192046 should fix your issue.
However, as you noted when possible, `partial_SVD` calls the sparse SVD which converts the tensor to numpy. If you need to use pytorch's SVD I could add a parameter to select which SVD to use (e.g. sparse SVD or regular SVD).

As a side note, why do you need to back-propagate through Tucker? Tucker provides an analytical solution to the decomposition by minimising the reconstruction error via ALS. As such not sure it makes sense to try to back-propagate through it.

**Comment by mfaraki** [comment]
Thanks for the update and useful package.
I am trying to backpropagate through Tucker (or HOSVD) on tensors just like doing that through SVD on matrices.
I think the solution in  [https://github.com/tensorly/tensorly/commit/4d249728ee1f4465dee470011119691a9b192046](url)
doesn't allow backpropagating through Tucker as it detaches the variables. What about using the PyTorch builtin functions instead and not converting anything to numpy matrices? For example, when doing eigen-decomposition on X * X.T calling torch.symeig or just calling torch.svd everywhere (this might be slow when a fraction of eigenvectors deemed).

Cheers

**Comment by JeanKossaifi** [comment]
I switched back to the scipy implementation as i) it's much faster when only a few of the eigenvalues are needed and ii) pytorch's SVD would raise memory errors even on medium size matrices. Additionally `torch.symeig` doesn't yet implement backward so have to stick with `torch.svd` for now.

I've started working on a fix for your use-case, will aim to push in the coming days -- currently on holidays with limited access to internet.

As a side note, Tucker via HOI, unlike HO-SVD, is an iterative procedure so not sure you'd accumulate useful gradients.

**Comment by JeanKossaifi** [comment]
I pushed a big commit (f28fd20b936c37e0a8d5ab04ad6f836a8ae8733a) that gives users the choice of the SVD to use. 

You can now specify in tucker or parafac `svd='truncated_svd'` which will use PyTorch's SVD and allow you to backpropagate through.

**Comment by Rachine** [comment]
To perform a TCL (Tensor Contraction Layer), I had to do that in pytorch. But now I am facing this issue from pytorch I think: https://github.com/pytorch/pytorch/issues/24900

**Comment by JeanKossaifi** [comment]
@Rachine TCL doesn't use SVD, just tensor contraction. Also, you can now use tensorly-torch which provides TCL in PyTorch!
