### ISSUE TITLE
segmentation fault when calling parafac()

### ISSUE THREAD

**Issue by liangkaihuan** [tensorly/tensorly#68]
Hi, I encountered the same error as  @ #16 , while I used numpy backen.
The version of **numpy** is 1.15.1 and the version of **tensorly** is 0.4.2.
Any solution for the issue? Thanks~

**Comment by liangkaihuan** [comment]
The computer memory is 240G.

**Comment by JeanKossaifi** [comment]
Thanks for reporting -- I thought this was fixed. Especially with 240G of RAM!

 Does the same minimal running example as in #16 cause a crash?
```
import numpy as np
import tensorly as tl
from tensorly.decomposition import parafac

A = tl.tensor(np.random.rand(256, 64, 3, 3))
factor = parafac(A, rank=4)
```

**Comment by liangkaihuan** [comment]
Yes!  When  `A.shape` is `(128, 64, 3, 3),` there is no problem. However, when the shape increase to `(256, 64, 3, 3)`， the segmentation fault happens. 
And I also try other function like `partial_tucker`, the codes work well. It seems like the  problem comes from  `parafac`

**Comment by liangkaihuan** [comment]
I changed to  `pytorch` backen, and the problem was solved when the shape was `(256, 64, 3, 3)`.
But when I continued increasing the size to `(512, 256, 3, 3)`, the memory error happened again.
The error is as follows:

> RuntimeError                              Traceback (most recent call last)
~/python3env/lib/python3.5/site-packages/tensorly/backend/pytorch_backend.py in partial_svd(matrix, n_eigenvecs)
    281         try:
--> 282             U, S, V = torch.svd(matrix, some=False)
    283             U, S, V = U[:, :n_eigenvecs], S[:n_eigenvecs], V.t()[:n_eigenvecs, :]
 RuntimeError: $ Torch: not enough memory: you tried to allocate 576GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:204

**Comment by liangkaihuan** [comment]
Oh！ I have found where the problem is. When I used `init='random'`, the code just worked well. The default value is `init='svd'`.

**Comment by JeanKossaifi** [comment]
I was going to suggest that as a fix :)

I think the issue comes from the fact that you have a rank of 4 but some modes of the tensor have dimension 3. As a result the transpose trick isn't used and SVD is applied to a huge unfolding matrix. This should be fixable though..

**Comment by liangkaihuan** [comment]
OK, thanks for your reply~~It's encouraging that this package is still keeping maintenance.

**Comment by JeanKossaifi** [comment]
We still actively developing, with lots more coming! Also welcoming contributions ;)

**Comment by Ruhallah93** [comment]
> Oh！ I have found where the problem is. When I used `init='random'`, the code just worked well. The default value is `init='svd'`.

I love you

**Comment by juroberttyb** [comment]
@liangkaihuan thank you for sharing it

**Comment by juroberttyb** [comment]
> Oh！ I have found where the problem is. When I used `init='random'`, the code just worked well. The default value is `init='svd'`.

thank you for sharing this!

**Comment by JeanKossaifi** [comment]
Given the comments, we could make `init='random'` the default or add clear documentation on handling memory issues.
