### ISSUE TITLE
Parafac init checking poorly coded

### ISSUE THREAD

**Issue by eriche7133** [tensorly/tensorly#69]
In initialize_factors, in order to check the initialization method (random or svd), the code used is:
if init is 'random':
elif init is 'svd':

This is overly constraining, as for example, the following code will throw a ValueError:
init_mode = 'random'
parafac(tensor,rank,init=init_mode)

Because init_mode is 'random' is False. Ideally the code should be:
if init == 'random':
elif init == 'svd':

as it is implemented in the tucker decomposition code.

**Comment by JeanKossaifi** [comment]
Agreed, thanks for flagging!
Are you happy to write a small pull-request to fix it?

**Comment by JeanKossaifi** [comment]
Fixed by #70.

Thanks for the quick fix @eriche7133!
