### ISSUE TITLE
Fix modes in PARAFAC

### ISSUE THREAD

**Issue by Legor** [tensorly/tensorly#72]
Hey everyone. Just wanted to add a feature idea here.

When using PARAFAC to process EEM data, it is very common to fix two modes (namely the modes for emission and excitation) to those values previously generated on a calibration dataset.
Thereby it is possible to estimate only the remaining mode (the concentration mode) and apply scaling factors that have been computed on the calibration data. 

I added this possibility on a personal fork of tensorly and got the expected outcome on a test dataset. However I'm not sure if my implementation will uphold your coding standards here .. since it basically just overwrites the values of a mode with given values after each iteration..

Also many other constraints (besides the non-negativity) are usually discussed together with PARAFAC, depending on the field of application. E.g. these include orthogonality and unimodality constraints on the loading matrices or the possibility to fix single components in a mode.

I think it is worth working on those additions especially since for PARAFAC there isn't any good free alternative to the well known MATLAB-Toolboxes.

Kind Greetings and thanks for your good work so far,
Gordon

**Comment by JeanKossaifi** [comment]
Hi @Legor, thanks for the suggestions and feedback!

Do you mean something similar to the [`partial_tucker`](http://tensorly.org/dev/modules/generated/tensorly.decomposition.partial_tucker.html#tensorly.decomposition.partial_tucker), but for CP -- i.e. decompose only along some of the modes? Or do you want to provide the factors of the decomposition for some of the modes?

It would be a nice addition - would be great if you wanted to help add it! Happy to have a look at your code/fork, and discuss the API!

Regarding other constraints, we do have orthogonalisation in CP thanks to @cswiercz, as well as non-negative CP. Which other constraints do you need for your work?

**Comment by Legor** [comment]
Greetings @JeanKossaifi, 
the second use case is what I'm currently interested in: providing the factors for some of the modes, or in some cases provide the factors for certain components of a mode. I can make a PR for this if you're interested. 

Regarding the many possibilites to extend PARAFAC it is worth looking at the N-way Toolbox (Matlab) by
Rasmus Bro & Claus A. Andersson, which you probably allready know. The code for this is freely available http://models.life.ku.dk/nwaytoolbox/download

**Comment by JeanKossaifi** [comment]
How would you propose adding this functionality -- it seems the soft approach would be to do this during initialisation, the other would be a hard assignment during optimisation?

We could add a parameter `fix_factors`, for instance a list of tuple `(mode, factor)`. It's a little trickier to provide a clean API for fixing only some of the components..

**Comment by JeanKossaifi** [comment]
Added in #171
