### ISSUE TITLE
weights in parafac decomposition

### ISSUE THREAD

**Issue by abhyudayasrinet** [tensorly/tensorly#82]
In parafac decomposition, the docs mention a "weights" parameter being returned as given below:

> weights : ndarray, optional
> Array of length rank of weights for each factor matrix. See the with_weights keyword attribute.

But they're not returned. Nor does the source have any mention of it.

**Comment by JeanKossaifi** [comment]
Thanks for reporting, I will update this. In the meantime, you can use the [`normalize_factors`](https://github.com/tensorly/tensorly/blob/master/tensorly/decomposition/candecomp_parafac.py) function to get these weights.
