### ISSUE TITLE
How to use the model_dot for tensor by tensor?

### ISSUE THREAD

**Issue by Yolanpera** [tensorly/tensorly#93]
I have seen the tensorly/tensorly/tenalg/n_mode_product.py,However, I want to use this function for tensor by tensor.Is that possible?

for example:
X =T.tensor([[[1, 13],
             [4, 16],
             [7, 19],
             [10, 22]],
            [[2, 14],
             [5, 17],
             [8, 20],
             [11, 23]]])

Y = T.tensor([[[1, 13],
             [4, 16],
             [7, 19],
             [10, 22]],
            [[2, 14],
             [5, 17],
             [8, 20],
             [11, 23]],
            [[3, 15],
             [6, 18],
             [9, 21],
             [12, 24]]])
How can I get the result of mode_dot(X, Y, 1)??

**Comment by Yolanpera** [comment]
I have seen the tensorly/tensorly/tenalg/n_mode_product.py,However, I want use this function for tensor by tensor.Is that possible?

**Comment by JeanKossaifi** [comment]
The n-mode product is only defined for tensor by matrix or tensor by vector products.
What you want is a general tensor contraction. I will add this soon! :)

**Comment by JeanKossaifi** [comment]
Done, you can use `tensorly.tenalg.contract`: http://tensorly.org/dev/modules/generated/tensorly.tenalg.contract.html#tensorly.tenalg.contract

**Comment by Yolanpera** [comment]
OK！ THANK YOU！
